export const genres = [
  { value: 1, label: "A Cappella" },
  { value: 2, label: "Abstract" },
  { value: 3, label: "Abstract Beats" },
  { value: 4, label: "Abstract Hip Hop" },
  { value: 5, label: "Abstract Idm" },
  { value: 6, label: "Abstractro" },
  { value: 7, label: "Accordion" },
  { value: 8, label: "Acid House" },
  { value: 9, label: "Acid Jazz" },
  { value: 10, label: "Acid Techno" },
  { value: 11, label: "Acousmatic" },
  { value: 12, label: "Acoustic Blues" },
  { value: 13, label: "Acoustic Pop" },
  { value: 14, label: "Adult Standards" },
  { value: 15, label: "African Percussion" },
  { value: 16, label: "African Rock" },
  { value: 17, label: "Afrikaans" },
  { value: 18, label: "Afrobeat" },
  { value: 19, label: "Afrobeats" },
  { value: 20, label: "Aggrotech" },
  { value: 21, label: "Albanian Pop" },
  { value: 22, label: "Album Rock" },
  { value: 23, label: "Albuquerque Indie" },
  { value: 24, label: "Alternative Americana" },
  { value: 25, label: "Alternative Country" },
  { value: 26, label: "Alternative Dance" },
  { value: 27, label: "Alternative Emo" },
  { value: 28, label: "Alternative Hardcore" },
  { value: 29, label: "Alternative Hip Hop" },
  { value: 30, label: "Alternative Metal" },
  { value: 31, label: "Alternative Metalcore" },
  { value: 32, label: "Alternative New Age" },
  { value: 33, label: "Alternative Pop" },
  { value: 34, label: "Alternative Pop Rock" },
  { value: 35, label: "Alternative R&b" },
  { value: 36, label: "Alternative Rock" },
  { value: 37, label: "Alternative Roots Rock" },
  { value: 38, label: "Ambeat" },
  { value: 39, label: "Ambient" },
  { value: 40, label: "Ambient Dub Techno" },
  { value: 41, label: "Ambient Fusion" },
  { value: 42, label: "Ambient Idm" },
  { value: 43, label: "Ambient Psychill" },
  { value: 44, label: "Ambient Trance" },
  { value: 45, label: "Anarcho-punk" },
  { value: 46, label: "Andean" },
  { value: 47, label: "Anime" },
  { value: 48, label: "Anime Score" },
  { value: 49, label: "Anti-folk" },
  { value: 50, label: "Antiviral Pop" },
  { value: 51, label: "Appalachian Folk" },
  { value: 52, label: "Arab Folk" },
  { value: 53, label: "Arab Pop" },
  { value: 54, label: "Arabesk" },
  { value: 55, label: "Argentine Indie" },
  { value: 56, label: "Argentine Reggae" },
  { value: 57, label: "Argentine Rock" },
  { value: 58, label: "Armenian Folk" },
  { value: 59, label: "Art Rock" },
  { value: 60, label: "Athens Indie" },
  { value: 61, label: "Atmospheric Black Metal" },
  { value: 62, label: "Atmospheric Post Rock" },
  { value: 63, label: "Atmospheric Post-metal" },
  { value: 64, label: "Aussietronica" },
  { value: 65, label: "Austindie" },
  { value: 66, label: "Australian Alternative Rock" },
  { value: 67, label: "Australian Country" },
  { value: 68, label: "Australian Dance" },
  { value: 69, label: "Australian Hip Hop" },
  { value: 70, label: "Australian Indie" },
  { value: 71, label: "Australian Pop" },
  { value: 72, label: "Austrian Hip Hop" },
  { value: 73, label: "Austropop" },
  { value: 74, label: "Avant-garde" },
  { value: 75, label: "Avant-garde Jazz" },
  { value: 76, label: "Avantgarde Metal" },
  { value: 77, label: "Axe" },
  { value: 78, label: "Azonto" },
  { value: 79, label: "Bachata" },
  { value: 80, label: "Baile Funk" },
  { value: 81, label: "Balearic" },
  { value: 82, label: "Balkan Brass" },
  { value: 83, label: "Banda" },
  { value: 84, label: "Bangla" },
  { value: 85, label: "Barbershop" },
  { value: 86, label: "Barnemusikk" },
  { value: 87, label: "Barnmusik" },
  { value: 88, label: "Baroque" },
  { value: 89, label: "Baroque Ensemble" },
  { value: 90, label: "Basque Rock" },
  { value: 91, label: "Bass Music" },
  { value: 92, label: "Bass Trip" },
  { value: 93, label: "Bassline" },
  { value: 94, label: "Bay Area Hip Hop" },
  { value: 95, label: "Beach Music" },
  { value: 96, label: "Beatdown" },
  { value: 97, label: "Beats & Rhymes" },
  { value: 98, label: "Bebop" },
  { value: 99, label: "Belgian Indie" },
  { value: 100, label: "Belgian Rock" },
  { value: 101, label: "Belly Dance" },
  { value: 102, label: "Belorush" },
  { value: 103, label: "Bemani" },
  { value: 104, label: "Benga" },
  { value: 105, label: "Bhangra" },
  { value: 106, label: "Big Band" },
  { value: 107, label: "Big Beat" },
  { value: 108, label: "Big Room" },
  { value: 109, label: "Black Death" },
  { value: 110, label: "Black Metal" },
  { value: 111, label: "Black Sludge" },
  { value: 112, label: "Black Thrash" },
  { value: 113, label: "Blackgaze" },
  { value: 114, label: "Blaskapelle" },
  { value: 115, label: "Bluegrass" },
  { value: 116, label: "Blues" },
  { value: 117, label: "Blues-rock" },
  { value: 118, label: "Blues-rock Guitar" },
  { value: 119, label: "Bmore" },
  { value: 120, label: "Bolero" },
  { value: 121, label: "Boogaloo" },
  { value: 122, label: "Boogie-woogie" },
  { value: 123, label: "Bossa Nova" },
  { value: 124, label: "Bossa Nova Jazz" },
  { value: 125, label: "Boston Rock" },
  { value: 126, label: "Bounce" },
  { value: 127, label: "Bouncy House" },
  { value: 128, label: "Bow Pop" },
  { value: 129, label: "Boy Band" },
  { value: 130, label: "Brass Band" },
  { value: 131, label: "Brass Ensemble" },
  { value: 132, label: "Brazilian Composition" },
  { value: 133, label: "Brazilian Gospel" },
  { value: 134, label: "Brazilian Hip Hop" },
  { value: 135, label: "Brazilian Indie" },
  { value: 136, label: "Brazilian Pop Music" },
  { value: 137, label: "Brazilian Reggae" },
  { value: 138, label: "Brazilian Rock" },
  { value: 139, label: "Breakbeat" },
  { value: 140, label: "Breakcore" },
  { value: 141, label: "Breaks" },
  { value: 142, label: "Brega" },
  { value: 143, label: "Brill Building Pop" },
  { value: 144, label: "Brit Funk" },
  { value: 145, label: "Britpop" },
  { value: 146, label: "British Blues" },
  { value: 147, label: "British Dance Band" },
  { value: 148, label: "British Folk" },
  { value: 149, label: "British Indie Rock" },
  { value: 150, label: "British Jazz" },
  { value: 151, label: "British Modern Jazz" },
  { value: 152, label: "British Orchestral" },
  { value: 153, label: "British Singer-songwriter" },
  { value: 154, label: "Brostep" },
  { value: 155, label: "Bubblegrunge" },
  { value: 156, label: "Bubblegum Dance" },
  { value: 157, label: "Bubblegum Pop" },
  { value: 158, label: "Bubbletrance" },
  { value: 159, label: "Buddhist Chant" },
  { value: 160, label: "Bulgarian Folk" },
  { value: 161, label: "Bulgarian Pop" },
  { value: 162, label: "Bulgarian Rock" },
  { value: 163, label: "Bulgarian Traditional" },
  { value: 164, label: "C-pop" },
  { value: 165, label: "C-pop Boy Group" },
  { value: 166, label: "C-pop Girl Group" },
  { value: 167, label: "C-pop Idol" },
  { value: 168, label: "C-pop Rap" },
  { value: 169, label: "C-pop Rock" },
  { value: 170, label: "Calm Pop" },
  { value: 171, label: "Calypso" },
  { value: 172, label: "Calypso Jazz" },
  { value: 173, label: "Cambodian Pop" },
  { value: 174, label: "Candombe" },
  { value: 175, label: "Canzone Napoletana" },
  { value: 176, label: "Cape Breton Folk" },
  { value: 177, label: "Cape Jazz" },
  { value: 178, label: "Capoeira" },
  { value: 179, label: "Cantonese Pop" },
  { value: 180, label: "Cantonese Rock" },
  { value: 181, label: "Cantopop" },
  { value: 182, label: "Cantopop Girl Group" },
  { value: 183, label: "Cantopop Idol" },
  { value: 184, label: "Cantopop Rap" },
  { value: 185, label: "Cantopop Rock" },
  { value: 186, label: "Cape Verdean Rock" },
  { value: 187, label: "Caribbean Rock" },
  { value: 188, label: "Carnaval" },
  { value: 189, label: "Cartoon Jingle" },
  { value: 190, label: "Celtic" },
  { value: 191, label: "Celtic Harp" },
  { value: 192, label: "Celtic Metal" },
  { value: 193, label: "Celtic Punk" },
  { value: 194, label: "Celtic Rock" },
  { value: 195, label: "Celtic Traditional" },
  { value: 196, label: "Central American Rock" },
  { value: 197, label: "Central Asian Folk" },
  { value: 198, label: "Central Asian Hip Hop" },
  { value: 199, label: "Central Asian Pop" },
  { value: 200, label: "Central European Folk" },
  { value: 201, label: "Central European Jazz" },
  { value: 202, label: "Central European Metal" },
  { value: 203, label: "Central European Pop" },
  { value: 204, label: "Central European Rock" },
  { value: 205, label: "Chamber Folk" },
  { value: 206, label: "Chamber Jazz" },
  { value: 207, label: "Chamber Pop" },
  { value: 208, label: "Chamber Psych" },
  { value: 209, label: "Chamber Rock" },
  { value: 210, label: "Chamorro" },
  { value: 211, label: "Chant" },
  { value: 212, label: "Chant Electronique" },
  { value: 213, label: "Chant Psychill" },
  { value: 214, label: "Chant Trance" },
  { value: 215, label: "Chanson" },
  { value: 216, label: "Chanson Folk" },
  { value: 217, label: "Chanson Rap" },
  { value: 218, label: "Chanson Rock" },
  { value: 219, label: "Chanson Traditional" },
  { value: 220, label: "Chaotic Hardcore" },
  { value: 221, label: "Chap-hop" },
  { value: 222, label: "Chicago Blues" },
  { value: 223, label: "Chicago House" },
  { value: 224, label: "Chicago Jazz" },
  { value: 225, label: "Chicano" },
  { value: 226, label: "Chicano Rap" },
  { value: 227, label: "Chicano Rock" },
  { value: 228, label: "Chicano Soul" },
  { value: 229, label: "Chicano Traditional" },
  { value: 230, label: "Children's" },
  { value: 231, label: "Chill" },
  { value: 232, label: "Chill Beats" },
  { value: 233, label: "Chill Christmas" },
  { value: 234, label: "Chill Hip Hop" },
  { value: 235, label: "Chill Instrumental" },
  { value: 236, label: "Chill Jazz" },
  { value: 237, label: "Chill Lounge" },
  { value: 238, label: "Chill Pop" },
  { value: 239, label: "Chill Rap" },
  { value: 240, label: "Chill Rock" },
  { value: 241, label: "Chill Step" },
  { value: 242, label: "Chill Wave" },
  { value: 243, label: "Chilled Jazz" },
  { value: 244, label: "Chillhop" },
  { value: 245, label: "Chillstep" },
  { value: 246, label: "Chillwave" },
  { value: 247, label: "Chinese Classical" },
  { value: 248, label: "Chinese Dance" },
  { value: 249, label: "Chinese Folk" },
  { value: 250, label: "Chinese Hip Hop" },
  { value: 251, label: "Chinese Indie" },
  { value: 252, label: "Chinese Jazz" },
  { value: 253, label: "Chinese Pop" },
  { value: 254, label: "Chinese Reggae" },
  { value: 255, label: "Chinese Rock" },
  { value: 256, label: "Chip Music" },
  { value: 257, label: "Chiptune" },
  { value: 258, label: "Choir" },
  { value: 259, label: "Choral" },
  { value: 260, label: "Choral Christmas" },
  { value: 261, label: "Choral Pop" },
  { value: 262, label: "Choral Rock" },
  { value: 263, label: "Choral Traditional" },
  { value: 264, label: "Christian" },
  { value: 265, label: "Christian Dance" },
  { value: 266, label: "Christian Hardcore" },
  { value: 267, label: "Christian Hip Hop" },
  { value: 268, label: "Christian Metal" },
  { value: 269, label: "Christian Pop" },
  { value: 270, label: "Christian Punk" },
  { value: 271, label: "Christian Rap" },
  { value: 272, label: "Christian Rock" },
  { value: 273, label: "Christmas" },
  { value: 273, label: "Christmas" },
  { value: 274, label: "Christmas Dance" },
  { value: 275, label: "Christmas Folk" },
  { value: 276, label: "Christmas Hip Hop" },
  { value: 277, label: "Christmas Jazz" },
  { value: 278, label: "Christmas Pop" },
  { value: 279, label: "Christmas Rock" },
  { value: 280, label: "Chutney" },
  { value: 281, label: "Cinematic" },
  { value: 282, label: "Cinematic Dubstep" },
  { value: 283, label: "Circus" },
  { value: 284, label: "Classic Blues" },
  { value: 285, label: "Classic Brazilian Pop" },
  { value: 286, label: "Classic Christian" },
  { value: 287, label: "Classic City Pop" },
  { value: 288, label: "Classic Country" },
  { value: 289, label: "Classic Dance" },
  { value: 290, label: "Classic Finnish Pop" },
  { value: 291, label: "Classic Finnish Rock" },
  { value: 292, label: "Classic Funk" },
  { value: 293, label: "Classic Garage Rock" },
  { value: 294, label: "Classic Girl Group" },
  { value: 295, label: "Classic Gospel" },
  { value: 296, label: "Classic Jazz" },
  { value: 297, label: "Classic Metal" },
  { value: 298, label: "Classic Nigerian Pop" },
  { value: 299, label: "Classic Norwegian Pop" },
  { value: 300, label: "Classic Norwegian Rock" },
  { value: 301, label: "Classic Pop" },
  { value: 302, label: "Classic Post-punk" },
  { value: 303, label: "Classic Prog Rock" },
  { value: 304, label: "Classic Punk" },
  { value: 305, label: "Classic R&B" },
  { value: 306, label: "Classic Reggae" },
  { value: 307, label: "Classic Rock" },
  { value: 308, label: "Classic Russian Pop" },
  { value: 309, label: "Classic Salsa" },
  { value: 310, label: "Classic Scottish Pop" },
  { value: 311, label: "Classic Singer-songwriter" },
  { value: 312, label: "Classic Soul" },
  { value: 313, label: "Classic Swedish Pop" },
  { value: 314, label: "Classic Swedish Rock" },
  { value: 315, label: "Classic Thrash" },
  { value: 316, label: "Classic Venezuelan Pop" },
  { value: 317, label: "Classical" },
  { value: 318, label: "Classical Crossover" },
  { value: 319, label: "Classical Performance" },
  { value: 320, label: "Close Harmony" },
  { value: 321, label: "Cloud Rap" },
  { value: 322, label: "Club" },
  { value: 323, label: "Club House" },
  { value: 324, label: "Club Pop" },
  { value: 325, label: "Club Rap" },
  { value: 326, label: "Cluster" },
  { value: 327, label: "Clyde's Top 100" },
  { value: 328, label: "Cocktail" },
  { value: 329, label: "Coldwave" },
  { value: 330, label: "College A Cappella" },
  { value: 331, label: "College Hip Hop" },
  { value: 332, label: "College Pop" },
  { value: 333, label: "College Rock" },
  { value: 334, label: "Colombian Pop" },
  { value: 335, label: "Colombian Rock" },
  { value: 336, label: "Comedy" },
  { value: 337, label: "Comedy Rap" },
  { value: 338, label: "Comic" },
  { value: 339, label: "Comic Book Soundtrack" },
  { value: 340, label: "Comic Strips" },
  { value: 341, label: "Commodore 64" },
  { value: 342, label: "Compas" },
  { value: 343, label: "Composed Music" },
  { value: 344, label: "Computer Music" },
  { value: 345, label: "Conjunto" },
  { value: 346, label: "Conscious Hip Hop" },
  { value: 347, label: "Contemporary Bluegrass" },
  { value: 348, label: "Contemporary Blues" },
  { value: 349, label: "Contemporary Celtic" },
  { value: 350, label: "Contemporary Christian" },
  { value: 351, label: "Contemporary Classical" },
  { value: 352, label: "Contemporary Country" },
  { value: 353, label: "Contemporary Folk" },
  { value: 354, label: "Contemporary Gospel" },
  { value: 355, label: "Contemporary Jazz" },
  { value: 356, label: "Contemporary R&B" },
  { value: 357, label: "Contemporary Singer-songwriter" },
  { value: 358, label: "Contemporary Soul" },
  { value: 359, label: "Cool Jazz" },
  { value: 360, label: "Cornet" },
  { value: 361, label: "Corpus Christi Indie" },
  { value: 362, label: "Corsican Folk" },
  { value: 363, label: "Cosmic" },
  { value: 364, label: "Cosmic American" },
  { value: 365, label: "Cosmic Blues" },
  { value: 366, label: "Cosmic Disco" },
  { value: 367, label: "Cosmic Jazz" },
  { value: 368, label: "Cosmic Lounge" },
  { value: 369, label: "Cosmic Pop" },
  { value: 370, label: "Cosmic Rock" },
  { value: 371, label: "Cosmic Soul" },
  { value: 372, label: "Country" },
  { value: 373, label: "Country Blues" },
  { value: 374, label: "Country Boogie" },
  { value: 375, label: "Country Christmas" },
  { value: 376, label: "Country Dawn" },
  { value: 377, label: "Country Folk" },
  { value: 378, label: "Country Gospel" },
  { value: 379, label: "Country Pop" },
  { value: 380, label: "Country Rap" },
  { value: 381, label: "Country Rock" },
  { value: 382, label: "Country Singer-songwriter" },
  { value: 383, label: "Country Soul" },
  { value: 384, label: "Country Swing" },
  { value: 385, label: "Cowpunk" },
  { value: 386, label: "Crabcore" },
  { value: 387, label: "Crack Rock" },
  { value: 388, label: "Crate Digger" },
  { value: 389, label: "Creaker" },
  { value: 390, label: "Creative" },
  { value: 391, label: "Creepy Music" },
  { value: 392, label: "Creole" },
  { value: 393, label: "Creole Folk" },
  { value: 394, label: "Creole Rock" },
  { value: 395, label: "Crossover Prog" },
  { value: 396, label: "Crossover Rock" },
  { value: 397, label: "Crossover Thrash" },
  { value: 398, label: "Crunk" },
  { value: 399, label: "Crunkcore" },
  { value: 400, label: "Crust Punk" },
  { value: 401, label: "Cubaton" },
  { value: 402, label: "Cumbia" },
  { value: 403, label: "Cumbia Pop" },
  { value: 404, label: "Cumbia Rock" },
  { value: 405, label: "Cyber Metal" },
  { value: 406, label: "Cybergrind" },
  { value: 407, label: "Cyberpunk" },
  { value: 408, label: "Cypriot Pop" },
  { value: 409, label: "Cypriot Rock" },
  { value: 410, label: "Czech Classical" },
  { value: 411, label: "Czech Folk" },
  { value: 412, label: "Czech Jazz" },
  { value: 413, label: "Czech Pop" },
  { value: 414, label: "Czech Rock" },
  { value: 415, label: "Dance" },
  { value: 416, label: "Dance Pop" },
  { value: 417, label: "Dance Rock" },
  { value: 418, label: "Dance-electronica" },
  { value: 419, label: "Dancehall" },
  { value: 420, label: "Dancepunk" },
  { value: 421, label: "Dark Ambient" },
  { value: 422, label: "Dark Christmas" },
  { value: 423, label: "Dark Country" },
  { value: 424, label: "Dark Electro" },
  { value: 425, label: "Dark Electro-Industrial" },
  { value: 426, label: "Dark Jazz" },
  { value: 427, label: "Dark Psytrance" },
  { value: 428, label: "Dark Rock" },
  { value: 429, label: "Dark Synth" },
  { value: 430, label: "Dark Trap" },
  { value: 431, label: "Dark Wave" },
  { value: 432, label: "Dark-folk" },
  { value: 433, label: "Dark-jazz" },
  { value: 434, label: "Dark-wave" },
  { value: 435, label: "Darkpsy" },
  { value: 436, label: "Darwin Indie" },
  { value: 437, label: "Dawn Pop" },
  { value: 438, label: "Dayton Indie" },
  { value: 439, label: "DC Hardcore" },
  { value: 440, label: "Death Industrial" },
  { value: 441, label: "Death Metal" },
  { value: 442, label: "Death-doom Metal" },
  { value: 443, label: "Deathcore" },
  { value: 444, label: "Debut Pop" },
  { value: 445, label: "Deep Christian" },
  { value: 446, label: "Deep Disco" },
  { value: 447, label: "Deep Euro House" },
  { value: 448, label: "Deep Folk" },
  { value: 449, label: "Deep Gothic" },
  { value: 450, label: "Deep House" },
  { value: 451, label: "Deep Pop" },
  { value: 452, label: "Deep Progressive House" },
  { value: 453, label: "Deep Soul House" },
  { value: 454, label: "Deep Tech House" },
  { value: 455, label: "Deep Vocal House" },
  { value: 456, label: "Delta Blues" },
  { value: 457, label: "Deltatronic" },
  { value: 458, label: "Demoscene" },
  { value: 459, label: "Desert Blues" },
  { value: 460, label: "Desert Folk" },
  { value: 461, label: "Desert Rock" },
  { value: 462, label: "Detroit Hip Hop" },
  { value: 463, label: "Detroit Rock" },
  { value: 464, label: "Detroit Techno" },
  { value: 465, label: "Deviant Pop" },
  { value: 466, label: "Digital Hardcore" },
  { value: 467, label: "Digiwave" },
  { value: 468, label: "Dingai Pop" },
  { value: 469, label: "Disco" },
  { value: 470, label: "Disco House" },
  { value: 471, label: "Disco Pop" },
  { value: 472, label: "Disco-funk" },
  { value: 473, label: "Disco-house" },
  { value: 474, label: "Disco-punk" },
  { value: 475, label: "Disco-rock" },
  { value: 476, label: "Diva House" },
  { value: 477, label: "Divan Indie" },
  { value: 478, label: "Djent" },
  { value: 479, label: "DnB" },
  { value: 480, label: "Doo-wop" },
  { value: 481, label: "Doom Metal" },
  { value: 482, label: "Doom Rock" },
  { value: 483, label: "Downtempo" },
  { value: 484, label: "Downwings" },
  { value: 485, label: "Dream Pop" },
  { value: 486, label: "Dream Rap" },
  { value: 487, label: "Dream Rock" },
  { value: 488, label: "Drift Phonk" },
  { value: 489, label: "Drone" },
  { value: 490, label: "Drone Ambient" },
  { value: 491, label: "Drone Blues" },
  { value: 492, label: "Drone Folk" },
  { value: 493, label: "Drone Metal" },
  { value: 494, label: "Drone Pop" },
  { value: 495, label: "Drone Rock" },
  { value: 496, label: "Drop Pop" },
  { value: 497, label: "Drum and Bass" },
  { value: 498, label: "Drumstep" },
  { value: 499, label: "Dub" },
  { value: 500, label: "Dub Metal" },
  { value: 501, label: "Dub Pop" },
  { value: 502, label: "Dub Punk" },
  { value: 503, label: "Dub Rap" },
  { value: 504, label: "Dub Reggae" },
  { value: 505, label: "Dub Rock" },
  { value: 506, label: "Dub-electronic" },
  { value: 507, label: "Dub-influenced Dubstep" },
  { value: 508, label: "Dub-style" },
  { value: 509, label: "Dub-techno" },
  { value: 510, label: "Dub-wise" },
  { value: 511, label: "Dubblues" },
  { value: 512, label: "Dubfolk" },
  { value: 513, label: "Dublin Indie" },
  { value: 514, label: "Dublin Metal" },
  { value: 515, label: "Dublin Punk" },
  { value: 516, label: "Dublin Rap" },
  { value: 517, label: "Dubpop" },
  { value: 518, label: "Dubreggae" },
  { value: 519, label: "Dubrock" },
  { value: 520, label: "Dubsoul" },
  { value: 521, label: "Dubwise" },
  { value: 522, label: "Duct Tape" },
  { value: 523, label: "Dungeon Synth" },
  { value: 524, label: "Dutch Metal" },
  { value: 525, label: "Dutch Pop" },
  { value: 526, label: "Dutch Rock" },
  { value: 527, label: "Dutch Techno" },
  { value: 528, label: "Dutchcore" },
  { value: 529, label: "Dystopia" },
  { value: 530, label: "Early Music" },
  { value: 531, label: "East African Pop" },
  { value: 532, label: "East African Rap" },
  { value: 533, label: "East Coast Hip Hop" },
  { value: 534, label: "East European Folk" },
  { value: 535, label: "East London Grime" },
  { value: 536, label: "East Texas Hip Hop" },
  { value: 537, label: "Eastern Bloc Punk" },
  { value: 538, label: "Eastern Classical" },
  { value: 539, label: "Eastern European Folk" },
  { value: 540, label: "Eastern European Hip Hop" },
  { value: 541, label: "Eastern European Pop" },
  { value: 542, label: "Eastern European Rock" },
  { value: 543, label: "Easy Listening" },
  { value: 544, label: "Eclectic" },
  { value: 545, label: "Eclectic Jazz" },
  { value: 546, label: "Eclectic Pop" },
  { value: 547, label: "Eclectic Rock" },
  { value: 548, label: "Eclectronic" },
  { value: 549, label: "Ecuadorian Pop" },
];
