export const genres = [
  { value: "A Cappella", label: "A Cappella" },
  { value: "Abstract", label: "Abstract" },
  { value: "Abstract Beats", label: "Abstract Beats" },
  { value: "Abstract Hip Hop", label: "Abstract Hip Hop" },
  { value: "Abstract Idm", label: "Abstract Idm" },
  { value: "Abstractro", label: "Abstractro" },
  { value: "Accordion", label: "Accordion" },
  { value: "Acid House", label: "Acid House" },
  { value: "Acid Jazz", label: "Acid Jazz" },
  { value: "Acid Techno", label: "Acid Techno" },
  { value: "Acousmatic", label: "Acousmatic" },
  { value: "Acoustic Blues", label: "Acoustic Blues" },
  { value: "Acoustic Pop", label: "Acoustic Pop" },
  { value: "Adult Standards", label: "Adult Standards" },
  { value: "African Percussion", label: "African Percussion" },
  { value: "African Rock", label: "African Rock" },
  { value: "Afrikaans", label: "Afrikaans" },
  { value: "Afrobeat", label: "Afrobeat" },
  { value: "Afrobeats", label: "Afrobeats" },
  { value: "Aggrotech", label: "Aggrotech" },
  { value: "Albanian Pop", label: "Albanian Pop" },
  { value: "Album Rock", label: "Album Rock" },
  { value: "Albuquerque Indie", label: "Albuquerque Indie" },
  { value: "Alternative Americana", label: "Alternative Americana" },
  { value: "Alternative Country", label: "Alternative Country" },
  { value: "Alternative Dance", label: "Alternative Dance" },
  { value: "Alternative Emo", label: "Alternative Emo" },
  { value: "Alternative Hardcore", label: "Alternative Hardcore" },
  { value: "Alternative Hip Hop", label: "Alternative Hip Hop" },
  { value: "Alternative Metal", label: "Alternative Metal" },
  { value: "Alternative Metalcore", label: "Alternative Metalcore" },
  { value: "Alternative New Age", label: "Alternative New Age" },
  { value: "Alternative Pop", label: "Alternative Pop" },
  { value: "Alternative Pop Rock", label: "Alternative Pop Rock" },
  { value: "Alternative R&b", label: "Alternative R&b" },
  { value: "Alternative Rock", label: "Alternative Rock" },
  { value: "Alternative Roots Rock", label: "Alternative Roots Rock" },
  { value: "Ambeat", label: "Ambeat" },
  { value: "Ambient", label: "Ambient" },
  { value: "Ambient Dub Techno", label: "Ambient Dub Techno" },
  { value: "Ambient Fusion", label: "Ambient Fusion" },
  { value: "Ambient Idm", label: "Ambient Idm" },
  { value: "Ambient Psychill", label: "Ambient Psychill" },
  { value: "Ambient Trance", label: "Ambient Trance" },
  { value: "Anarcho-punk", label: "Anarcho-punk" },
  { value: "Andean", label: "Andean" },
  { value: "Anime", label: "Anime" },
  { value: "Anime Score", label: "Anime Score" },
  { value: "Anti-folk", label: "Anti-folk" },
  { value: "Antiviral Pop", label: "Antiviral Pop" },
  { value: "Appalachian Folk", label: "Appalachian Folk" },
  { value: "Arab Folk", label: "Arab Folk" },
  { value: "Arab Pop", label: "Arab Pop" },
  { value: "Arabesk", label: "Arabesk" },
  { value: "Argentine Indie", label: "Argentine Indie" },
  { value: "Argentine Reggae", label: "Argentine Reggae" },
  { value: "Argentine Rock", label: "Argentine Rock" },
  { value: "Armenian Folk", label: "Armenian Folk" },
  { value: "Art Rock", label: "Art Rock" },
  { value: "Athens Indie", label: "Athens Indie" },
  { value: "Atmospheric Black Metal", label: "Atmospheric Black Metal" },
  { value: "Atmospheric Post Rock", label: "Atmospheric Post Rock" },
  { value: "Atmospheric Post-metal", label: "Atmospheric Post-metal" },
  { value: "Aussietronica", label: "Aussietronica" },
  { value: "Austindie", label: "Austindie" },
  { value: "Australian Alternative Rock", label: "Australian Alternative Rock" },
  { value: "Australian Country", label: "Australian Country" },
  { value: "Australian Dance", label: "Australian Dance" },
  { value: "Australian Hip Hop", label: "Australian Hip Hop" },
  { value: "Australian Indie", label: "Australian Indie" },
  { value: "Australian Pop", label: "Australian Pop" },
  { value: "Austrian Hip Hop", label: "Austrian Hip Hop" },
  { value: "Austropop", label: "Austropop" },
  { value: "Avant-garde", label: "Avant-garde" },
  { value: "Avant-garde Jazz", label: "Avant-garde Jazz" },
  { value: "Avantgarde Metal", label: "Avantgarde Metal" },
  { value: "Axe", label: "Axe" },
  { value: "Azonto", label: "Azonto" },
  { value: "Bachata", label: "Bachata" },
  { value: "Baile Funk", label: "Baile Funk" },
  { value: "Balearic", label: "Balearic" },
  { value: "Balkan Brass", label: "Balkan Brass" },
  { value: "Banda", label: "Banda" },
  { value: "Bangla", label: "Bangla" },
  { value: "Barbershop", label: "Barbershop" },
  { value: "Barnemusikk", label: "Barnemusikk" },
  { value: "Barnmusik", label: "Barnmusik" },
  { value: "Baroque", label: "Baroque" },
  { value: "Baroque Ensemble", label: "Baroque Ensemble" },
  { value: "Basque Rock", label: "Basque Rock" },
  { value: "Bass Music", label: "Bass Music" },
  { value: "Bass Trip", label: "Bass Trip" },
  { value: "Bassline", label: "Bassline" },
  { value: "Bay Area Hip Hop", label: "Bay Area Hip Hop" },
  { value: "Beach Music", label: "Beach Music" },
  { value: "Beatdown", label: "Beatdown" },
  { value: "Beats & Rhymes", label: "Beats & Rhymes" },
  { value: "Bebop", label: "Bebop" },
  { value: "Belgian Indie", label: "Belgian Indie" },
  { value: "Belgian Rock", label: "Belgian Rock" },
  { value: "Belly Dance", label: "Belly Dance" },
  { value: "Belorush", label: "Belorush" },
  { value: "Bemani", label: "Bemani" },
  { value: "Benga", label: "Benga" },
  { value: "Bhangra", label: "Bhangra" },
  { value: "Big Band", label: "Big Band" },
  { value: "Big Beat", label: "Big Beat" },
  { value: "Big Room", label: "Big Room" },
  { value: "Black Death", label: "Black Death" },
  { value: "Black Metal", label: "Black Metal" },
  { value: "Black Sludge", label: "Black Sludge" },
  { value: "Black Thrash", label: "Black Thrash" },
  { value: "Blackgaze", label: "Blackgaze" },
  { value: "Blaskapelle", label: "Blaskapelle" },
  { value: "Bluegrass", label: "Bluegrass" },
  { value: "Blues", label: "Blues" },
  { value: "Blues-rock", label: "Blues-rock" },
  { value: "Blues-rock Guitar", label: "Blues-rock Guitar" },
  { value: "Bmore", label: "Bmore" },
  { value: "Bolero", label: "Bolero" },
  { value: "Boogaloo", label: "Boogaloo" },
  { value: "Boogie-woogie", label: "Boogie-woogie" },
  { value: "Bossa Nova", label: "Bossa Nova" },
  { value: "Bouncy House", label: "Bouncy House" },
  { value: "Bounce", label: "Bounce" },
  { value: "Bow Pop", label: "Bow Pop" },
  { value: "Boy Pop", label: "Boy Pop" },
  { value: "Boy Band", label: "Boy Band" },
  { value: "Boygroup", label: "Boygroup" },
  { value: "Brazilian Indie", label: "Brazilian Indie" },
  { value: "Brazilian Pop", label: "Brazilian Pop" },
  { value: "Breakbeat", label: "Breakbeat" },
  { value: "Breakcore", label: "Breakcore" },
  { value: "Breaks", label: "Breaks" },
  { value: "Breton Folk", label: "Breton Folk" },
  { value: "Brill Building Pop", label: "Brill Building Pop" },
  { value: "Brit Funk", label: "Brit Funk" },
  { value: "Britcore", label: "Britcore" },
  { value: "Britpop", label: "Britpop" },
  { value: "British Dance Band", label: "British Dance Band" },
  { value: "British Folk", label: "British Folk" },
  { value: "British Hip Hop", label: "British Hip Hop" },
  { value: "British Jazz", label: "British Jazz" },
  { value: "British Metal", label: "British Metal" },
  { value: "British Punk", label: "British Punk" },
  { value: "Brostep", label: "Brostep" },
  { value: "Brutal Death Metal", label: "Brutal Death Metal" },
  { value: "Brutal Deathcore", label: "Brutal Deathcore" },
  { value: "Bubblegum Dance", label: "Bubblegum Dance" },
  { value: "Bubblegum Pop", label: "Bubblegum Pop" },
  { value: "Bulgaria", label: "Bulgaria" },
  { value: "Bulgarian Folk", label: "Bulgarian Folk" },
  { value: "Bunraku", label: "Bunraku" },
  { value: "Burlesque", label: "Burlesque" },
  { value: "C-pop", label: "C-pop" },
  { value: "Ca Christian Pop", label: "Ca Christian Pop" },
  { value: "Calgary Indie", label: "Calgary Indie" },
  { value: "Cali Rap", label: "Cali Rap" },
  { value: "Calypso", label: "Calypso" },
  { value: "Calypso Be", label: "Calypso Be" },
  { value: "Canadian Country", label: "Canadian Country" },
  { value: "Canadian Folk", label: "Canadian Folk" },
  { value: "Canadian Hip Hop", label: "Canadian Hip Hop" },
  { value: "Canadian Indie", label: "Canadian Indie" },
  { value: "Canadian Pop", label: "Canadian Pop" },
  { value: "Canadian Post-rock", label: "Canadian Post-rock" },
  { value: "Canadian Singer-songwriter", label: "Canadian Singer-songwriter" },
  { value: "Canadian Trap", label: "Canadian Trap" },
  { value: "Canberra Indie", label: "Canberra Indie" },
  { value: "Cantique", label: "Cantique" },
  { value: "Cape Breton Fiddle", label: "Cape Breton Fiddle" },
  { value: "Cape Jazz", label: "Cape Jazz" },
  { value: "Cape Verdean Folk", label: "Cape Verdean Folk" },
  { value: "Capoeira", label: "Capoeira" },
  { value: "Candomble", label: "Candomble" },
  { value: "Canterbury Scene", label: "Canterbury Scene" },
  { value: "Canzone Napoletana", label: "Canzone Napoletana" },
  { value: "Canzone Siciliane", label: "Canzone Siciliane" },
  { value: "Cascadia Indie", label: "Cascadia Indie" },
  { value: "Catstep", label: "Catstep" },
  { value: "Caucasian Folk", label: "Caucasian Folk" },
  { value: "Caucasian Jazz", label: "Caucasian Jazz" },
  { value: "Celtic", label: "Celtic" },
  { value: "Celtic Folk", label: "Celtic Folk" },
  { value: "Celtic Metal", label: "Celtic Metal" },
  { value: "Celtic Punk", label: "Celtic Punk" },
  { value: "Celtic Rock", label: "Celtic Rock" },
  { value: "Central Asian Folk", label: "Central Asian Folk" },
  { value: "Chamber Ensemble", label: "Chamber Ensemble" },
  { value: "Chamber Folk", label: "Chamber Folk" },
  { value: "Chamber Orchestra", label: "Chamber Orchestra" },
  { value: "Chamber Pop", label: "Chamber Pop" },
  { value: "Chamber Psych", label: "Chamber Psych" },
  { value: "Chanson", label: "Chanson" },
  { value: "Chant", label: "Chant" },
  { value: "Chapman Stick", label: "Chapman Stick" },
  { value: "Chassidic Pop", label: "Chassidic Pop" },
  { value: "Chattanooga Indie", label: "Chattanooga Indie" },
  { value: "Chattanooga Metal", label: "Chattanooga Metal" },
  { value: "Chicago Blues", label: "Chicago Blues" },
  { value: "Chicago House", label: "Chicago House" },
  { value: "Chicago Punk", label: "Chicago Punk" },
  { value: "Children's Music", label: "Children's Music" },
  { value: "Chilean Indie", label: "Chilean Indie" },
  { value: "Chilean Pop", label: "Chilean Pop" },
  { value: "Chill House", label: "Chill House" },
  { value: "Chill Lounge", label: "Chill Lounge" },
  { value: "Chill Out", label: "Chill Out" },
  { value: "Chill R&b", label: "Chill R&b" },
  { value: "Chill Step", label: "Chill Step" },
  { value: "Chillwave", label: "Chillwave" },
  { value: "Chinese Experimental", label: "Chinese Experimental" },
  { value: "Chiptune", label: "Chiptune" },
  { value: "Choir", label: "Choir" },
  { value: "Chopped And Screwed", label: "Chopped And Screwed" },
  { value: "Choral", label: "Choral" },
  { value: "Choro", label: "Choro" },
  { value: "Chorus", label: "Chorus" },
  { value: "Christian Alternative", label: "Christian Alternative" },
  { value: "Christian Contemporary", label: "Christian Contemporary" },
  { value: "Christian Country", label: "Christian Country" },
  { value: "Christian Dance", label: "Christian Dance" },
  { value: "Christian Hard Rock", label: "Christian Hard Rock" },
  { value: "Christian Hip Hop", label: "Christian Hip Hop" },
  { value: "Christian Metal", label: "Christian Metal" },
  { value: "Christian Music", label: "Christian Music" },
  { value: "Christian Pop", label: "Christian Pop" },
  { value: "Christian Punk", label: "Christian Punk" },
  { value: "Christian Rock", label: "Christian Rock" },
  { value: "Christmas", label: "Christmas" },
  { value: "Christmas Instrumental", label: "Christmas Instrumental" },
  { value: "Christmas Jazz", label: "Christmas Jazz" },
  { value: "Christmas Orchestra", label: "Christmas Orchestra" },
  { value: "Christmas Pop", label: "Christmas Pop" },
  { value: "Christmas Worship", label: "Christmas Worship" },
  { value: "Chutney", label: "Chutney" },
  { value: "Cincinnati Indie", label: "Cincinnati Indie" },
  { value: "Circus", label: "Circus" },
  { value: "Classic Acoustic Blues", label: "Classic Acoustic Blues" },
  { value: "Classic Brazilian Pop", label: "Classic Brazilian Pop" },
  { value: "Classic Canadian Rock", label: "Classic Canadian Rock" },
  { value: "Classic Christian Rock", label: "Classic Christian Rock" },
  { value: "Classic Country", label: "Classic Country" },
  { value: "Classic Dance", label: "Classic Dance" },
  { value: "Classic Dubstep", label: "Classic Dubstep" },
  { value: "Classic Eurodisco", label: "Classic Eurodisco" },
  { value: "Classic Finnish Rock", label: "Classic Finnish Rock" },
  { value: "Classic Girl Group", label: "Classic Girl Group" },
  { value: "Classic Gospel", label: "Classic Gospel" },
  { value: "Classic Hardstyle", label: "Classic Hardstyle" },
  { value: "Classic House", label: "Classic House" },
  { value: "Classic Iskelma", label: "Classic Iskelma" },
  { value: "Classic Jazz", label: "Classic Jazz" },
  { value: "Classic Korean Pop", label: "Classic Korean Pop" },
  { value: "Classic Peruvian Pop", label: "Classic Peruvian Pop" },
  { value: "Classic Polish Pop", label: "Classic Polish Pop" },
  { value: "Classic Progressive House", label: "Classic Progressive House" },
  { value: "Classic R&b", label: "Classic R&b" },
  { value: "Classic Reggae", label: "Classic Reggae" },
  { value: "Classic Rock", label: "Classic Rock" },
  { value: "Classic Roots Reggae", label: "Classic Roots Reggae" },
  { value: "Classic Russian Rock", label: "Classic Russian Rock" },
  { value: "Classic Soul", label: "Classic Soul" },
  { value: "Classic Swedish Pop", label: "Classic Swedish Pop" },
  { value: "Classic Turkish Pop", label: "Classic Turkish Pop" },
  { value: "Classic Venezuelan Pop", label: "Classic Venezuelan Pop" },
  { value: "Classical", label: "Classical" },
  { value: "Classical Baritone", label: "Classical Baritone" },
  { value: "Classical Cello", label: "Classical Cello" },
  { value: "Classical Clarinet", label: "Classical Clarinet" },
  { value: "Classical Countertenor", label: "Classical Countertenor" },
  { value: "Classical Guitar", label: "Classical Guitar" },
  { value: "Classical Organ", label: "Classical Organ" },
  { value: "Classical Performance", label: "Classical Performance" },
  { value: "Classical Piano", label: "Classical Piano" },
  { value: "Classical Soprano", label: "Classical Soprano" },
  { value: "Classical Tenor", label: "Classical Tenor" },
  { value: "Classical Trombone", label: "Classical Trombone" },
  { value: "Classical Trumpet", label: "Classical Trumpet" },
  { value: "Classical Violin", label: "Classical Violin" },
  { value: "Classify", label: "Classify" },
  { value: "Claw Hammer Banjo", label: "Claw Hammer Banjo" },
  { value: "Clean Comedy", label: "Clean Comedy" },
  { value: "Cleveland Metal", label: "Cleveland Metal" },
  { value: "Clipper Ship", label: "Clipper Ship" },
  { value: "Club", label: "Club" },
  { value: "Club Dance", label: "Club Dance" },
  { value: "Club Jazz", label: "Club Jazz" },
  { value: "Club House", label: "Club House" },
  { value: "Club Rock", label: "Club Rock" },
  { value: "Club Techno", label: "Club Techno" },
  { value: "Coffin Scorer", label: "Coffin Scorer" },
  { value: "College Rock", label: "College Rock" },
  { value: "Colombian Hip Hop", label: "Colombian Hip Hop" },
  { value: "Colombian Pop", label: "Colombian Pop" },
  { value: "Columbus Indie", label: "Columbus Indie" },
  { value: "Comedy", label: "Comedy" },
  { value: "Comedy Rap", label: "Comedy Rap" },
  { value: "Comic", label: "Comic" },
  { value: "Comic Book", label: "Comic Book" },
  { value: "Comic Metal", label: "Comic Metal" },
  { value: "Comic Opera", label: "Comic Opera" },
  { value: "Commercial Folk", label: "Commercial Folk" },
  { value: "Commercial House", label: "Commercial House" },
  { value: "Commercial Jazz", label: "Commercial Jazz" },
  { value: "Commercial Reggae", label: "Commercial Reggae" },
  { value: "Commercial Soundtrack", label: "Commercial Soundtrack" },
  { value: "Commercial Techno", label: "Commercial Techno" },
  { value: "Commercial Trance", label: "Commercial Trance" },
  { value: "Commodore 64", label: "Commodore 64" },
  { value: "Comptine", label: "Comptine" },
  { value: "Conjunto", label: "Conjunto" },
  { value: "Contemporary", label: "Contemporary" },
  { value: "Contemporary Bluegrass", label: "Contemporary Bluegrass" },
  { value: "Contemporary Blues", label: "Contemporary Blues" },
  { value: "Contemporary Celtic", label: "Contemporary Celtic" },
  { value: "Contemporary Choir", label: "Contemporary Choir" },
  { value: "Contemporary Classical", label: "Contemporary Classical" },
  { value: "Contemporary Country", label: "Contemporary Country" },
  { value: "Contemporary Folk", label: "Contemporary Folk" },
  { value: "Contemporary Gospel", label: "Contemporary Gospel" },
  { value: "Contemporary Instrumental", label: "Contemporary Instrumental" },
  { value: "Contemporary Jazz", label: "Contemporary Jazz" },
  { value: "Contemporary Opera", label: "Contemporary Opera" },
  { value: "Contemporary Pop", label: "Contemporary Pop" },
  { value: "Contemporary R&b", label: "Contemporary R&b" },
  { value: "Contemporary Singer-songwriter", label: "Contemporary Singer-songwriter" },
  { value: "Contemporary Soul", label: "Contemporary Soul" },
  { value: "Contemporary Soundtrack", label: "Contemporary Soundtrack" },
  { value: "Contemporary Trance", label: "Contemporary Trance" },
  { value: "Cool Jazz", label: "Cool Jazz" },
  { value: "Country", label: "Country" },
  { value: "Country Blues", label: "Country Blues" },
  { value: "Country Boogie", label: "Country Boogie" },
  { value: "Country Dawn", label: "Country Dawn" },
  { value: "Country Folk", label: "Country Folk" },
  { value: "Country Gospel", label: "Country Gospel" },
  { value: "Country Honk", label: "Country Honk" },
  { value: "Country Pop", label: "Country Pop" },
  { value: "Country Rap", label: "Country Rap" },
  { value: "Country Rock", label: "Country Rock" },
  { value: "Country Trap", label: "Country Trap" },
  { value: "Cover", label: "Cover" },
  { value: "Covers", label: "Covers" },
  { value: "Cowboy Country", label: "Cowboy Country" },
  { value: "Cowboy Pop", label: "Cowboy Pop" },
  { value: "Cowboy Psychedelic", label: "Cowboy Psychedelic" },
  { value: "Cpop", label: "Cpop" },
  { value: "Craft", label: "Craft" },
  { value: "Cretan Folk", label: "Cretan Folk" },
  { value: "Crime", label: "Crime" },
  { value: "Croatian Pop", label: "Croatian Pop" },
  { value: "Crossover Folk", label: "Crossover Folk" },
  { value: "Crossover Jazz", label: "Crossover Jazz" },
  { value: "Crossover Prog", label: "Crossover Prog" },
  { value: "Crossover Thrash", label: "Crossover Thrash" },
  { value: "Crunk", label: "Crunk" },
  { value: "Crunkcore", label: "Crunkcore" },
  { value: "Crust Punk", label: "Crust Punk" },
  { value: "Crystal Case", label: "Crystal Case" },
  { value: "Cuban", label: "Cuban" },
  { value: "Cuban Folk", label: "Cuban Folk" },
  { value: "Cumbia", label: "Cumbia" },
  { value: "Cumbia Pop", label: "Cumbia Pop" },
  { value: "Cumbia Sonidera", label: "Cumbia Sonidera" },
  { value: "Current Classical", label: "Current Classical" },
  { value: "Current Rock", label: "Current Rock" },
  { value: "Cyber Metal", label: "Cyber Metal" },
  { value: "Cyber Pop", label: "Cyber Pop" },
  { value: "Cybercore", label: "Cybercore" },
  { value: "Czech Classical", label: "Czech Classical" },
  { value: "Czech Country", label: "Czech Country" },
  { value: "Czech Folk", label: "Czech Folk" },
  { value: "Czech Hip Hop", label: "Czech Hip Hop" },
  { value: "Czech Indie", label: "Czech Indie" },
  { value: "Czech Pop", label: "Czech Pop" },
  { value: "Danish Country", label: "Danish Country" },
  { value: "Danish Folk", label: "Danish Folk" },
  { value: "Danish Hip Hop", label: "Danish Hip Hop" },
  { value: "Danish Indie", label: "Danish Indie" },
  { value: "Danish Pop", label: "Danish Pop" },
  { value: "Dark Ambient", label: "Dark Ambient" },
  { value: "Dark Clubbing", label: "Dark Clubbing" },
  { value: "Dark Country", label: "Dark Country" },
  { value: "Dark Disco", label: "Dark Disco" },
  { value: "Dark Electro", label: "Dark Electro" },
  { value: "Dark Folk", label: "Dark Folk" },
  { value: "Dark Jazz", label: "Dark Jazz" },
  { value: "Dark Post-punk", label: "Dark Post-punk" },
  { value: "Dark Psytrance", label: "Dark Psytrance" },
  { value: "Dark R&b", label: "Dark R&b" },
  { value: "Dark Shoegaze", label: "Dark Shoegaze" },
  { value: "Dark Step", label: "Dark Step" },
  { value: "Dark Synth", label: "Dark Synth" },
  { value: "Dark Techno", label: "Dark Techno" },
  { value: "Dark Wave", label: "Dark Wave" },
  { value: "Darkpop", label: "Darkpop" },
  { value: "Darkside", label: "Darkside" },
  { value: "Darkstep", label: "Darkstep" },
  { value: "Darkwave", label: "Darkwave" },
  { value: "Datapop", label: "Datapop" },
  { value: "Death 'n' Roll", label: "Death 'n' Roll" },
  { value: "Death Blues", label: "Death Blues" },
  { value: "Death Core", label: "Death Core" },
  { value: "Death Doom", label: "Death Doom" },
  { value: "Death Folk", label: "Death Folk" },
  { value: "Death Industrial", label: "Death Industrial" },
  { value: "Death Metal", label: "Death Metal" },
  { value: "Death Rock", label: "Death Rock" },
  { value: "Death Step", label: "Death Step" },
  { value: "Deathcore", label: "Deathcore" },
  { value: "Deathgrind", label: "Deathgrind" },
  { value: "Deathsynth", label: "Deathsynth" },
  { value: "Decibel", label: "Decibel" },
  { value: "Deep Acoustic", label: "Deep Acoustic" },
  { value: "Deep Adult Standards", label: "Deep Adult Standards" },
  { value: "Deep Alt-country", label: "Deep Alt-country" },
  { value: "Deep Alternative", label: "Deep Alternative" },
  { value: "Deep Art Pop", label: "Deep Art Pop" },
  { value: "Deep Big Room", label: "Deep Big Room" },
  { value: "Deep Bluegrass", label: "Deep Bluegrass" },
  { value: "Deep Breakcore", label: "Deep Breakcore" },
  { value: "Deep Britpop", label: "Deep Britpop" },
  { value: "Deep Christian Hard Rock", label: "Deep Christian Hard Rock" },
  { value: "Deep Classic Hard Rock", label: "Deep Classic Hard Rock" },
  { value: "Deep Classic Jazz", label: "Deep Classic Jazz" },
  { value: "Deep Comedy", label: "Deep Comedy" },
  { value: "Deep Disco", label: "Deep Disco" },
  { value: "Deep East Coast Hip Hop", label: "Deep East Coast Hip Hop" },
  { value: "Deep East Coast Indie", label: "Deep East Coast Indie" },
  { value: "Deep Filthstep", label: "Deep Filthstep" },
  { value: "Deep Flow", label: "Deep Flow" },
  { value: "Deep Funk", label: "Deep Funk" },
  { value: "Deep German Hip Hop", label: "Deep German Hip Hop" },
  { value: "Deep Gothic Post-punk", label: "Deep Gothic Post-punk" },
  { value: "Deep Hard Rock", label: "Deep Hard Rock" },
  { value: "Deep Hardcore Punk", label: "Deep Hardcore Punk" },
  { value: "Deep House", label: "Deep House" },
  { value: "Deep Indie Rock", label: "Deep Indie Rock" },
  { value: "Deep Indie Singer-songwriter", label: "Deep Indie Singer-songwriter" },
  { value: "Deep Liquid", label: "Deep Liquid" },
  { value: "Deep Latin Jazz", label: "Deep Latin Jazz" },
  { value: "Deep Metalcore", label: "Deep Metalcore" },
  { value: "Deep Motown", label: "Deep Motown" },
  { value: "Deep New Wave", label: "Deep New Wave" },
  { value: "Deep Northern Soul", label: "Deep Northern Soul" },
  { value: "Deep Pop Emo", label: "Deep Pop Emo" },
  { value: "Deep Pop-punk", label: "Deep Pop-punk" },
  { value: "Deep Power-pop", label: "Deep Power-pop" },
  { value: "Deep Psytrance", label: "Deep Psytrance" },
  { value: "Deep R&b", label: "Deep R&b" },
  { value: "Deep Ragga", label: "Deep Ragga" },
  { value: "Deep Reggaeton", label: "Deep Reggaeton" },
  { value: "Deep Southern Soul", label: "Deep Southern Soul" },
  { value: "Deep Talent Show", label: "Deep Talent Show" },
  { value: "Deep Tech House", label: "Deep Tech House" },
  { value: "Deep Thrash", label: "Deep Thrash" },
  { value: "Deep Traditional Bluegrass", label: "Deep Traditional Bluegrass" },
  { value: "Deep Tropical House", label: "Deep Tropical House" },
  { value: "Deep Underground Hip Hop", label: "Deep Underground Hip Hop" },
  { value: "Deep Vocal Jazz", label: "Deep Vocal Jazz" },
  { value: "Deep West Coast Hip Hop", label: "Deep West Coast Hip Hop" },
  { value: "Deephouse", label: "Deephouse" },
  { value: "Deepneurofunk", label: "Deepneurofunk" },
  { value: "Deepsoul", label: "Deepsoul" },
  { value: "Deeptalent", label: "Deeptalent" },
  { value: "Delta Blues", label: "Delta Blues" },
  { value: "Denpa-kei", label: "Denpa-kei" },
  { value: "Desert Blues", label: "Desert Blues" },
  { value: "Desert Rock", label: "Desert Rock" },
  { value: "Desi Hip Hop", label: "Desi Hip Hop" },
  { value: "Desi Pop", label: "Desi Pop" },
  { value: "Detroit Hip Hop", label: "Detroit Hip Hop" },
  { value: "Detroit Indie", label: "Detroit Indie" },
  { value: "Detroit Jazz", label: "Detroit Jazz" },
  { value: "Detroit Techno", label: "Detroit Techno" },
  { value: "Digital Hardcore", label: "Digital Hardcore" },
  { value: "Diva House", label: "Diva House" },
  { value: "Djent", label: "Djent" },
  { value: "Django", label: "Django" },
  { value: "Doowop", label: "Doowop" },
  { value: "Doom Metal", label: "Doom Metal" },
  { value: "Doomcore", label: "Doomcore" },
  { value: "Doomdeath", label: "Doomdeath" },
  { value: "Double", label: "Double" },
  { value: "Downtempo", label: "Downtempo" },
  { value: "Dream Pop", label: "Dream Pop" },
  { value: "Drift Phonk", label: "Drift Phonk" },
  { value: "Drill", label: "Drill" },
  { value: "Drum And Bass", label: "Drum And Bass" },
  { value: "Drumstep", label: "Drumstep" },
  { value: "Dub", label: "Dub" },
  { value: "Dub Jazz", label: "Dub Jazz" },
  { value: "Dub Poetry", label: "Dub Poetry" },
  { value: "Dubstep", label: "Dubstep" },
  { value: "Dulcimer", label: "Dulcimer" },
  { value: "Dutch Blues", label: "Dutch Blues" },
  { value: "Dutch Country", label: "Dutch Country" },
  { value: "Dutch Folk", label: "Dutch Folk" },
  { value: "Dutch Hip Hop", label: "Dutch Hip Hop" },
  { value: "Dutch House", label: "Dutch House" },
  { value: "Dutch Indie", label: "Dutch Indie" },
  { value: "Dutch Pop", label: "Dutch Pop" },
  { value: "Dutch Punk", label: "Dutch Punk" },
  { value: "Dutch Reggae", label: "Dutch Reggae" },
  { value: "Dutch Trance", label: "Dutch Trance" },
  { value: "Easy Listening", label: "Easy Listening" },
  { value: "Ebm", label: "Ebm" },
  { value: "Eclectic", label: "Eclectic" },
  { value: "Eclectic Pop", label: "Eclectic Pop" },
  { value: "Eclectic Rock", label: "Eclectic Rock" },
  { value: "Electro", label: "Electro" },
  { value: "Electro Pop", label: "Electro Pop" },
  { value: "Electro-acoustic", label: "Electro-acoustic" },
  { value: "Electro-clash", label: "Electro-clash" },
  { value: "Electro-dub", label: "Electro-dub" },
  { value: "Electro-funk", label: "Electro-funk" },
  { value: "Electro-groove", label: "Electro-groove" },
  { value: "Electro-industrial", label: "Electro-industrial" },
  { value: "Electro-jazz", label: "Electro-jazz" },
  { value: "Electro-lounge", label: "Electro-lounge" },
  { value: "Electro-minimal", label: "Electro-minimal" },
  { value: "Electro-swing", label: "Electro-swing" },
  { value: "Electroacoustic", label: "Electroacoustic" },
  { value: "Electroclash", label: "Electroclash" },
  { value: "Electrofunk", label: "Electrofunk" },
  { value: "Electrogroove", label: "Electrogroove" },
  { value: "Electrohouse", label: "Electrohouse" },
  { value: "Electroindustrial", label: "Electroindustrial" },
  { value: "Electrojazz", label: "Electrojazz" },
  { value: "Electrolounge", label: "Electrolounge" },
  { value: "Electrominimal", label: "Electrominimal" },
  { value: "Electropop", label: "Electropop" },
  { value: "Electroswing", label: "Electroswing" },
  { value: "Electroworld", label: "Electroworld" },
  { value: "Emo", label: "Emo" },
  { value: "Emo Pop", label: "Emo Pop" },
  { value: "Emo Rap", label: "Emo Rap" },
  { value: "Emocore", label: "Emocore" },
  { value: "Emoindie", label: "Emoindie" },
  { value: "Empty", label: "Empty" },
  { value: "Enka", label: "Enka" },
  { value: "Ennui", label: "Ennui" },
  { value: "Ephemeral", label: "Ephemeral" },
  { value: "Epic Doom", label: "Epic Doom" },
  { value: "Epic Metal", label: "Epic Metal" },
  { value: "Epic Rock", label: "Epic Rock" },
  { value: "Epic Soundtrack", label: "Epic Soundtrack" },
  { value: "Ethiopian Folk", label: "Ethiopian Folk" },
  { value: "Euphoric Hardstyle", label: "Euphoric Hardstyle" },
  { value: "Euphoric Trance", label: "Euphoric Trance" },
  { value: "European Classical", label: "European Classical" },
  { value: "European Country", label: "European Country" },
  { value: "European Folk", label: "European Folk" },
  { value: "European Hip Hop", label: "European Hip Hop" },
  { value: "European Jazz", label: "European Jazz" },
  { value: "European Pop", label: "European Pop" },
  { value: "Eurotechno", label: "Eurotechno" },
  { value: "Eurotrash", label: "Eurotrash" },
  { value: "Experimental", label: "Experimental" },
  { value: "Experimental Folk", label: "Experimental Folk" },
  { value: "Experimental Hip Hop", label: "Experimental Hip Hop" },
  { value: "Experimental House", label: "Experimental House" },
  { value: "Experimental Jazz", label: "Experimental Jazz" },
  { value: "Experimental Metal", label: "Experimental Metal" },
  { value: "Experimental Pop", label: "Experimental Pop" },
  { value: "Experimental Rock", label: "Experimental Rock" },
  { value: "Experimental Sound", label: "Experimental Sound" },
  { value: "Extreme Metal", label: "Extreme Metal" },
  { value: "Extreme Noise", label: "Extreme Noise" },
  { value: "Extreme Power Metal", label: "Extreme Power Metal" },
  { value: "Extreme Progressive Metal", label: "Extreme Progressive Metal" },
  { value: "Fado", label: "Fado" },
  { value: "Fandangos", label: "Fandangos" },
  { value: "Farmers Market", label: "Farmers Market" },
  { value: "Female Metal", label: "Female Metal" },
  { value: "Filthstep", label: "Filthstep" },
  { value: "Finnish Folk", label: "Finnish Folk" },
  { value: "Finnish Hip Hop", label: "Finnish Hip Hop" },
  { value: "Finnish Jazz", label: "Finnish Jazz" },
  { value: "Finnish Metal", label: "Finnish Metal" },
  { value: "Finnish Pop", label: "Finnish Pop" },
  { value: "Finnish Punk", label: "Finnish Punk" },
  { value: "Finnish Reggae", label: "Finnish Reggae" },
  { value: "Finnish Rock", label: "Finnish Rock" },
  { value: "Flamenco", label: "Flamenco" },
  { value: "Flash", label: "Flash" },
  { value: "Flip Flop", label: "Flip Flop" },
  { value: "Flow", label: "Flow" },
  { value: "Flower Metal", label: "Flower Metal" },
  { value: "Folk", label: "Folk" },
  { value: "Folk Metal", label: "Folk Metal" },
  { value: "Folk Pop", label: "Folk Pop" },
  { value: "Folk Punk", label: "Folk Punk" },
  { value: "Folk Rock", label: "Folk Rock" },
  { value: "Folk-pop", label: "Folk-pop" },
  { value: "Folkrock", label: "Folkrock" },
  { value: "Football Soundtrack", label: "Football Soundtrack" },
  { value: "French Blues", label: "French Blues" },
  { value: "French Classical", label: "French Classical" },
  { value: "French Folk", label: "French Folk" },
  { value: "French Hip Hop", label: "French Hip Hop" },
  { value: "French Indie", label: "French Indie" },
  { value: "French Jazz", label: "French Jazz" },
  { value: "French Metal", label: "French Metal" },
  { value: "French Pop", label: "French Pop" },
  { value: "French Punk", label: "French Punk" },
  { value: "French Reggae", label: "French Reggae" },
  { value: "French Rock", label: "French Rock" },
  { value: "French Soundtrack", label: "French Soundtrack" },
  { value: "Freestyle", label: "Freestyle" },
  { value: "Freestyle Hip Hop", label: "Freestyle Hip Hop" },
  { value: "Freesynth", label: "Freesynth" },
  { value: "Fremantle Indie", label: "Fremantle Indie" },
  { value: "Fremantle Jazz", label: "Fremantle Jazz" },
  { value: "Fremantle Pop", label: "Fremantle Pop" },
  { value: "Fremantle Rock", label: "Fremantle Rock" },
  { value: "Fresh Finds", label: "Fresh Finds" },
  { value: "Fresh Pop", label: "Fresh Pop" },
  { value: "Fresh Wave", label: "Fresh Wave" },
  { value: "Fun House", label: "Fun House" },
  { value: "Fun Metal", label: "Fun Metal" },
  { value: "Funk", label: "Funk" },
  { value: "Funk Metal", label: "Funk Metal" },
  { value: "Funk Pop", label: "Funk Pop" },
  { value: "Funk Rock", label: "Funk Rock" },
  { value: "Funk-a-riffic", label: "Funk-a-riffic" },
  { value: "Funk-n-jazz", label: "Funk-n-jazz" },
  { value: "Funkadelic", label: "Funkadelic" },
  { value: "Funkdj", label: "Funkdj" },
  { value: "Funkmetal", label: "Funkmetal" },
  { value: "Funkrock", label: "Funkrock" },
  { value: "Funky Breaks", label: "Funky Breaks" },
  { value: "Funky Country", label: "Funky Country" },
  { value: "Funky Folk", label: "Funky Folk" },
  { value: "Funky Groove", label: "Funky Groove" },
  { value: "Funky Jazz", label: "Funky Jazz" },
  { value: "Funky Lounge", label: "Funky Lounge" },
  { value: "Funky Pop", label: "Funky Pop" },
  { value: "Funky Rap", label: "Funky Rap" },
  { value: "Funky Rock", label: "Funky Rock" },
  { value: "Future Funk", label: "Future Funk" },
  { value: "Future Garage", label: "Future Garage" },
  { value: "Future Hop", label: "Future Hop" },
  { value: "Future House", label: "Future House" },
  { value: "Future Jazz", label: "Future Jazz" },
  { value: "Future Pop", label: "Future Pop" },
  { value: "Future Rock", label: "Future Rock" },
  { value: "Future Techno", label: "Future Techno" },
  { value: "Futurednb", label: "Futurednb" },
  { value: "Futurerock", label: "Futurerock" },
  { value: "Gabber", label: "Gabber" },
  { value: "Galego Hip Hop", label: "Galego Hip Hop" },
  { value: "Galego Jazz", label: "Galego Jazz" },
  { value: "Galego Pop", label: "Galego Pop" },
  { value: "Galego Rock", label: "Galego Rock" },
  { value: "Garage", label: "Garage" },
  { value: "Garage Pop", label: "Garage Pop" },
  { value: "Garage Punk", label: "Garage Punk" },
  { value: "Garage Rock", label: "Garage Rock" },
  { value: "Garage Soul", label: "Garage Soul" },
  { value: "Garagebop", label: "Garagebop" },
  { value: "Garagepop", label: "Garagepop" },
  { value: "Garagepunk", label: "Garagepunk" },
  { value: "Garagerock", label: "Garagerock" },
  { value: "Gass", label: "Gass" },
  { value: "Gbmusic", label: "Gbmusic" },
  { value: "Genre-busting", label: "Genre-busting" },
  { value: "Georgian Folk", label: "Georgian Folk" },
  { value: "Georgian Hip Hop", label: "Georgian Hip Hop" },
  { value: "Georgian Jazz", label: "Georgian Jazz" },
  { value: "Georgian Pop", label: "Georgian Pop" },
  { value: "Georgian Rock", label: "Georgian Rock" },
  { value: "German Blues", label: "German Blues" },
  { value: "German Classical", label: "German Classical" },
  { value: "German Folk", label: "German Folk" },
  { value: "German Hip Hop", label: "German Hip Hop" },
  { value: "German Indie", label: "German Indie" },
  { value: "German Jazz", label: "German Jazz" },
  { value: "German Metal", label: "German Metal" },
  { value: "German Pop", label: "German Pop" },
  { value: "German Punk", label: "German Punk" },
  { value: "German Reggae", label: "German Reggae" },
  { value: "German Rock", label: "German Rock" },
  { value: "Glam", label: "Glam" },
  { value: "Glam Metal", label: "Glam Metal" },
  { value: "Glam Rock", label: "Glam Rock" },
  { value: "Glitch Hop", label: "Glitch Hop" },
  { value: "Glitch Pop", label: "Glitch Pop" },
  { value: "Glitch-hop", label: "Glitch-hop" },
  { value: "Glitchpop", label: "Glitchpop" },
  { value: "Gloom", label: "Gloom" },
  { value: "Gloom Pop", label: "Gloom Pop" },
  { value: "Gloom Rock", label: "Gloom Rock" },
  { value: "Gloompunk", label: "Gloompunk" },
  { value: "Gloomsoul", label: "Gloomsoul" },
  { value: "Gltch", label: "Gltch" },
  { value: "Gnawa", label: "Gnawa" },
  { value: "Goa", label: "Goa" },
  { value: "Goa Trance", label: "Goa Trance" },
  { value: "Goregrind", label: "Goregrind" },
  { value: "Gospel", label: "Gospel" },
  { value: "Goth Metal", label: "Goth Metal" },
  { value: "Goth Pop", label: "Goth Pop" },
  { value: "Goth Rap", label: "Goth Rap" },
  { value: "Goth Rock", label: "Goth Rock" },
  { value: "Gothabilly", label: "Gothabilly" },
  { value: "Gothcore", label: "Gothcore" },
  { value: "Gothic Americana", label: "Gothic Americana" },
  { value: "Gothic Blues", label: "Gothic Blues" },
  { value: "Gothic Country", label: "Gothic Country" },
  { value: "Gothic Electronica", label: "Gothic Electronica" },
  { value: "Gothic Folk", label: "Gothic Folk" },
  { value: "Gothic Hip Hop", label: "Gothic Hip Hop" },
  { value: "Gothic Jazz", label: "Gothic Jazz" },
  { value: "Gothic Metal", label: "Gothic Metal" },
  { value: "Gothic Pop", label: "Gothic Pop" },
  { value: "Gothic Punk", label: "Gothic Punk" },
  { value: "Gothic Rap", label: "Gothic Rap" },
  { value: "Gothic Rock", label: "Gothic Rock" },
  { value: "Gothrock", label: "Gothrock" },
  { value: "Grime", label: "Grime" },
  { value: "Grime Pop", label: "Grime Pop" },
  { value: "Grindcore", label: "Grindcore" },
  { value: "Groove", label: "Groove" },
  { value: "Groove Metal", label: "Groove Metal" },
  { value: "Groove Pop", label: "Groove Pop" },
  { value: "Groove Rock", label: "Groove Rock" },
  { value: "Groovemetal", label: "Groovemetal" },
  { value: "Groovepop", label: "Groovepop" },
  { value: "Grooverock", label: "Grooverock" },
  { value: "Groovy", label: "Groovy" },
  { value: "Guitar House", label: "Guitar House" },
  { value: "Guitar Jazz", label: "Guitar Jazz" },
  { value: "Guitar Pop", label: "Guitar Pop" },
  { value: "Guitar Rock", label: "Guitar Rock" },
  { value: "Guitar-driven", label: "Guitar-driven" },
  { value: "Guitarfolk", label: "Guitarfolk" },
  { value: "Guitarhero", label: "Guitarhero" },
  { value: "Guitarpop", label: "Guitarpop" },
  { value: "Guitarrock", label: "Guitarrock" },
  { value: "Gypsy Folk", label: "Gypsy Folk" },
  { value: "Gypsy Hip Hop", label: "Gypsy Hip Hop" },
  { value: "Gypsy Jazz", label: "Gypsy Jazz" },
  { value: "Gypsy Metal", label: "Gypsy Metal" },
  { value: "Gypsy Pop", label: "Gypsy Pop" },
  { value: "Gypsy Punk", label: "Gypsy Punk" },
  { value: "Gypsy Rock", label: "Gypsy Rock" },
  { value: "Handpan", label: "Handpan" },
  { value: "Happy Hardcore", label: "Happy Hardcore" },
  { value: "Hard House", label: "Hard House" },
  { value: "Hard Pop", label: "Hard Pop" },
  { value: "Hard Rock", label: "Hard Rock" },
  { value: "Hard Techno", label: "Hard Techno" },
  { value: "Hard Trance", label: "Hard Trance" },
  { value: "Hardbeat", label: "Hardbeat" },
  { value: "Hardcore", label: "Hardcore" },
  { value: "Hardcore Hip Hop", label: "Hardcore Hip Hop" },
  { value: "Hardcore Punk", label: "Hardcore Punk" },
  { value: "Hardcore Rock", label: "Hardcore Rock" },
  { value: "Hardcore Rap", label: "Hardcore Rap" },
  { value: "Harem Metal", label: "Harem Metal" },
  { value: "Harem Punk", label: "Harem Punk" },
  { value: "Harlem Hip Hop", label: "Harlem Hip Hop" },
  { value: "Harlem Jazz", label: "Harlem Jazz" },
  { value: "Harlem Pop", label: "Harlem Pop" },
  { value: "Harlem Rock", label: "Harlem Rock" },
  { value: "Harmony", label: "Harmony" },
  { value: "Harmony Pop", label: "Harmony Pop" },
  { value: "Harp", label: "Harp" },
  { value: "Harp Jazz", label: "Harp Jazz" },
  { value: "Harp Pop", label: "Harp Pop" },
  { value: "Harp Rock", label: "Harp Rock" },
  { value: "Heartland Rock", label: "Heartland Rock" },
  { value: "Heavy Metal", label: "Heavy Metal" },
  { value: "Heavy Pop", label: "Heavy Pop" },
  { value: "Heavy Rock", label: "Heavy Rock" },
  { value: "Heavy Trance", label: "Heavy Trance" },
  { value: "Heavy-blues", label: "Heavy-blues" },
  { value: "Heavy-country", label: "Heavy-country" },
  { value: "Heavyfolk", label: "Heavyfolk" },
  { value: "Heavyfusion", label: "Heavyfusion" },
  { value: "Heavygroove", label: "Heavygroove" },
  { value: "Heavyjazz", label: "Heavyjazz" },
  { value: "Heavyminimals", label: "Heavyminimals" },
  { value: "Heavymetal", label: "Heavymetal" },
  { value: "Heavypop", label: "Heavypop" },
  { value: "Heavyprog", label: "Heavyprog" },
  { value: "Heavypsychedelia", label: "Heavypsychedelia" },
  { value: "Heavypunk", label: "Heavypunk" },
  { value: "Heavyreggae", label: "Heavyreggae" },
  { value: "Heavyrock", label: "Heavyrock" },
  { value: "Heavytechno", label: "Heavytechno" },
  { value: "Heavywave", label: "Heavywave" },
  { value: "High-energy", label: "High-energy" },
  { value: "Highlife", label: "Highlife" },
  { value: "Hip Hop", label: "Hip Hop" },
  { value: "Hip Hop Soul", label: "Hip Hop Soul" },
  { value: "Hip Pop", label: "Hip Pop" },
  { value: "Hiphop", label: "Hiphop" },
  { value: "Hiphouse", label: "Hiphouse" },
  { value: "Hiphopsoul", label: "Hiphopsoul" },
  { value: "Hipjazz", label: "Hipjazz" },
  { value: "Hipno", label: "Hipno" },
  { value: "Hipnocore", label: "Hipnocore" },
  { value: "Hipnohouse", label: "Hipnohouse" },
  { value: "Hipnometal", label: "Hipnometal" },
  { value: "Hipnonoise", label: "Hipnonoise" },
  { value: "Hipnoreggae", label: "Hipnoreggae" },
  { value: "Hipnopop", label: "Hipnopop" },
  { value: "Hipnorock", label: "Hipnorock" },
  { value: "Hiptech", label: "Hiptech" },
  { value: "Hiptrance", label: "Hiptrance" },
  { value: "Holy Hip Hop", label: "Holy Hip Hop" },
  { value: "Horror Metal", label: "Horror Metal" },
  { value: "Horror Pop", label: "Horror Pop" },
  { value: "Horror Punk", label: "Horror Punk" },
  { value: "Horror Rap", label: "Horror Rap" },
  { value: "Horror Rock", label: "Horror Rock" },
  { value: "Horror-core", label: "Horror-core" },
  { value: "Horrorcore", label: "Horrorcore" },
  { value: "House", label: "House" },
  { value: "House Pop", label: "House Pop" },
  { value: "House Rock", label: "House Rock" },
  { value: "House-blues", label: "House-blues" },
  { value: "House-country", label: "House-country" },
  { value: "Housefolk", label: "Housefolk" },
  { value: "Housefusion", label: "Housefusion" },
  { value: "Housegroove", label: "Housegroove" },
  { value: "Housejazz", label: "Housejazz" },
  { value: "Housemetal", label: "Housemetal" },
  { value: "Housenoise", label: "Housenoise" },
  { value: "Housereggae", label: "Housereggae" },
  { value: "Housewave", label: "Housewave" },
  { value: "Houseworld", label: "Houseworld" },
  { value: "Housepop", label: "Housepop" },
  { value: "Housepunk", label: "Housepunk" },
  { value: "Housetrance", label: "Housetrance" },
  { value: "Hypno-pop", label: "Hypno-pop" },
  { value: "Hypno-rock", label: "Hypno-rock" },
  { value: "Hypnohouse", label: "Hypnohouse" },
  { value: "Hypnonoise", label: "Hypnonoise" },
  { value: "Hypnopop", label: "Hypnopop" },
  { value: "Hypnorock", label: "Hypnorock" },
  { value: "Hypnotic House", label: "Hypnotic House" },
  { value: "Hypnotic Jazz", label: "Hypnotic Jazz" },
  { value: "Hypnotic Pop", label: "Hypnotic Pop" },
  { value: "Hypnotic Rock", label: "Hypnotic Rock" },
  { value: "Hypnotronica", label: "Hypnotronica" },
  { value: "Hypnotronix", label: "Hypnotronix" },
  { value: "Ibiza", label: "Ibiza" },
  { value: "Ibiza House", label: "Ibiza House" },
  { value: "Ibiza Pop", label: "Ibiza Pop" },
  { value: "Ibiza Rock", label: "Ibiza Rock" },
  { value: "Icelandic Folk", label: "Icelandic Folk" },
  { value: "Icelandic Hip Hop", label: "Icelandic Hip Hop" },
  { value: "Icelandic Jazz", label: "Icelandic Jazz" },
  { value: "Icelandic Pop", label: "Icelandic Pop" },
  { value: "Icelandic Rock", label: "Icelandic Rock" },
  { value: "Idm", label: "Idm" },
  { value: "Idm Hip Hop", label: "Idm Hip Hop" },
  { value: "Idm Jazz", label: "Idm Jazz" },
  { value: "Idm Pop", label: "Idm Pop" },
  { value: "Idm Rock", label: "Idm Rock" },
  { value: "Idmpop", label: "Idmpop" },
  { value: "Idmrock", label: "Idmrock" },
  { value: "Indie", label: "Indie" },
  { value: "Indie Americana", label: "Indie Americana" },
  { value: "Indie Blues", label: "Indie Blues" },
  { value: "Indie Country", label: "Indie Country" },
  { value: "Indie Dream Pop", label: "Indie Dream Pop" },
  { value: "Indie Electronica", label: "Indie Electronica" },
  { value: "Indie Emo", label: "Indie Emo" },
  { value: "Indie Folk", label: "Indie Folk" },
  { value: "Indie Hip Hop", label: "Indie Hip Hop" },
  { value: "Indie Jazz", label: "Indie Jazz" },
  { value: "Indie Metal", label: "Indie Metal" },
  { value: "Indie Pop", label: "Indie Pop" },
  { value: "Indie Poptronica", label: "Indie Poptronica" },
  { value: "Indie Psych", label: "Indie Psych" },
  { value: "Indie Punk", label: "Indie Punk" },
  { value: "Indie Rap", label: "Indie Rap" },
  { value: "Indie Rock", label: "Indie Rock" },
  { value: "Indie Shoegaze", label: "Indie Shoegaze" },
  { value: "Indie Soul", label: "Indie Soul" },
  { value: "Indie Techno", label: "Indie Techno" },
  { value: "Indie Trance", label: "Indie Trance" },
  { value: "Indie-folk", label: "Indie-folk" },
  { value: "Indie-jazz", label: "Indie-jazz" },
  { value: "Indie-punk", label: "Indie-punk" },
  { value: "Indiepop", label: "Indiepop" },
  { value: "Indierap", label: "Indierap" },
  { value: "Indierock", label: "Indierock" },
  { value: "Industrial", label: "Industrial" },
  { value: "Industrial Hip Hop", label: "Industrial Hip Hop" },
  { value: "Industrial Jazz", label: "Industrial Jazz" },
  { value: "Industrial Metal", label: "Industrial Metal" },
  { value: "Industrial Pop", label: "Industrial Pop" },
  { value: "Industrial Rap", label: "Industrial Rap" },
  { value: "Industrial Rock", label: "Industrial Rock" },
  { value: "Instrumental", label: "Instrumental" },
  { value: "Instrumental Americana", label: "Instrumental Americana" },
  { value: "Instrumental Blues", label: "Instrumental Blues" },
  { value: "Instrumental Classical", label: "Instrumental Classical" },
  { value: "Instrumental Country", label: "Instrumental Country" },
  { value: "Instrumental Electronica", label: "Instrumental Electronica" },
  { value: "Instrumental Folk", label: "Instrumental Folk" },
  { value: "Instrumental Hip Hop", label: "Instrumental Hip Hop" },
  { value: "Instrumental Jazz", label: "Instrumental Jazz" },
  { value: "Instrumental Metal", label: "Instrumental Metal" },
  { value: "Instrumental Pop", label: "Instrumental Pop" },
  { value: "Instrumental Rap", label: "Instrumental Rap" },
  { value: "Instrumental Rock", label: "Instrumental Rock" },
  { value: "Instrumental Techno", label: "Instrumental Techno" },
  { value: "Instrumental Trance", label: "Instrumental Trance" },
  { value: "Intelligent Drum", label: "Intelligent Drum" },
  { value: "Intelligent Dnb", label: "Intelligent Dnb" },
  { value: "Intelligent Hip Hop", label: "Intelligent Hip Hop" },
  { value: "Intelligent Jazz", label: "Intelligent Jazz" },
  { value: "Intelligent Pop", label: "Intelligent Pop" },
  { value: "Intelligent Rock", label: "Intelligent Rock" },
  { value: "Intelligent Techno", label: "Intelligent Techno" },
  { value: "Intelligent Trance", label: "Intelligent Trance" },
  { value: "Intelligent-pop", label: "Intelligent-pop" },
  { value: "Intelligent-trance", label: "Intelligent-trance" },
  { value: "Intelligentdnb", label: "Intelligentdnb" },
  { value: "Intelligentpop", label: "Intelligentpop" },
  { value: "Intelligentrock", label: "Intelligentrock" },
  { value: "Intelligenttechno", label: "Intelligenttechno" },
  { value: "Italo", label: "Italo" },
  { value: "Italo House", label: "Italo House" },
  { value: "Italo Pop", label: "Italo Pop" },
  { value: "Italo Rock", label: "Italo Rock" },
  { value: "Italian Classical", label: "Italian Classical" },
  { value: "Italian Folk", label: "Italian Folk" },
  { value: "Italian Hip Hop", label: "Italian Hip Hop" },
  { value: "Italian Jazz", label: "Italian Jazz" },
  { value: "Italian Pop", label: "Italian Pop" },
  { value: "Italian Rock", label: "Italian Rock" },
  { value: "J", label: "J" },
  { value: "J Pop", label: "J Pop" },
  { value: "J Rap", label: "J Rap" },
  { value: "J Rock", label: "J Rock" },
  { value: "J-folk", label: "J-folk" },
  { value: "J-fusion", label: "J-fusion" },
  { value: "J-jazz", label: "J-jazz" },
  { value: "J-pop", label: "J-pop" },
  { value: "J-rap", label: "J-rap" },
  { value: "J-rock", label: "J-rock" },
  { value: "Jamaican Folk", label: "Jamaican Folk" },
  { value: "Jamaican Hip Hop", label: "Jamaican Hip Hop" },
  { value: "Jamaican Jazz", label: "Jamaican Jazz" },
  { value: "Jamaican Pop", label: "Jamaican Pop" },
  { value: "Jamaican Rock", label: "Jamaican Rock" },
  { value: "Jangle Pop", label: "Jangle Pop" },
  { value: "Jangle Punk", label: "Jangle Punk" },
  { value: "Jangle Rock", label: "Jangle Rock" },
  { value: "Janglepop", label: "Janglepop" },
  { value: "Janglepunk", label: "Janglepunk" },
  { value: "Janglerock", label: "Janglerock" },
  { value: "Jam", label: "Jam" },
  { value: "Jam Blues", label: "Jam Blues" },
  { value: "Jam Country", label: "Jam Country" },
  { value: "Jam Electronica", label: "Jam Electronica" },
  { value: "Jam Folk", label: "Jam Folk" },
  { value: "Jam Jazz", label: "Jam Jazz" },
  { value: "Jam Pop", label: "Jam Pop" },
  { value: "Jam Rock", label: "Jam Rock" },
  { value: "Jamjazz", label: "Jamjazz" },
  { value: "Jammin", label: "Jammin" },
  { value: "Jazcore", label: "Jazcore" },
  { value: "Jazz", label: "Jazz" },
  { value: "Jazz Americana", label: "Jazz Americana" },
  { value: "Jazz Blues", label: "Jazz Blues" },
  { value: "Jazz Folk", label: "Jazz Folk" },
  { value: "Jazz Fusion", label: "Jazz Fusion" },
  { value: "Jazz House", label: "Jazz House" },
  { value: "Jazz Metal", label: "Jazz Metal" },
  { value: "Jazz Pop", label: "Jazz Pop" },
  { value: "Jazz Rap", label: "Jazz Rap" },
  { value: "Jazz Rock", label: "Jazz Rock" },
  { value: "Jazz Soul", label: "Jazz Soul" },
  { value: "Jazz Trance", label: "Jazz Trance" },
  { value: "Jazzcore", label: "Jazzcore" },
  { value: "Jazzfolk", label: "Jazzfolk" },
  { value: "Jazzfusion", label: "Jazzfusion" },
  { value: "Jazzhouse", label: "Jazzhouse" },
  { value: "Jazzjazz", label: "Jazzjazz" },
  { value: "Jazzmetal", label: "Jazzmetal" },
  { value: "Jazzpop", label: "Jazzpop" },
  { value: "Jazzrap", label: "Jazzrap" },
  { value: "Jazzrock", label: "Jazzrock" },
  { value: "Jazzsoul", label: "Jazzsoul" },
  { value: "Jazztechno", label: "Jazztechno" },
  { value: "Jazztrance", label: "Jazztrance" },
  { value: "Jungle", label: "Jungle" },
  { value: "Jungle Pop", label: "Jungle Pop" },
  { value: "Jungle Rock", label: "Jungle Rock" },
  { value: "Jungle Techno", label: "Jungle Techno" },
  { value: "Junglepop", label: "Junglepop" },
  { value: "Junglepunk", label: "Junglepunk" },
  { value: "Jungletechno", label: "Jungletechno" },
  { value: "Jump Blues", label: "Jump Blues" },
  { value: "Jump Rock", label: "Jump Rock" },
  { value: "Jump-up", label: "Jump-up" },
  { value: "Junglepop", label: "Junglepop" },
  { value: "Junglepunk", label: "Junglepunk" },
  { value: "Jump Rock", label: "Jump Rock" },
  { value: "Jump-up", label: "Jump-up" },
  { value: "Junglepunk", label: "Junglepunk" },
  { value: "Jump Rock", label: "Jump Rock" },
  { value: "Jump-up", label: "Jump-up" },
  { value: "K Pop", label: "K Pop" },
  { value: "K Rap", label: "K Rap" },
  { value: "K Rock", label: "K Rock" },
  { value: "K-hiphop", label: "K-hiphop" },
  { value: "K-pop", label: "K-pop" },
  { value: "K-rap", label: "K-rap" },
  { value: "K-rock", label: "K-rock" },
  { value: "Kaleidoscopic Rock", label: "Kaleidoscopic Rock" },
  { value: "Kawaii", label: "Kawaii" },
  { value: "Kawaii Pop", label: "Kawaii Pop" },
  { value: "Kawaii Punk", label: "Kawaii Punk" },
  { value: "Kawaii Rock", label: "Kawaii Rock" },
  { value: "Kayokyoku", label: "Kayokyoku" },
  { value: "Klezmer", label: "Klezmer" },
  { value: "Klezmer Pop", label: "Klezmer Pop" },
  { value: "Klezmer Rock", label: "Klezmer Rock" },
  { value: "Korean Classical", label: "Korean Classical" },
  { value: "Korean Folk", label: "Korean Folk" },
  { value: "Korean Jazz", label: "Korean Jazz" },
  { value: "Korean Pop", label: "Korean Pop" },
  { value: "Korean Rock", label: "Korean Rock" },
  { value: "Krautrock", label: "Krautrock" },
  { value: "Kwaito", label: "Kwaito" },
  { value: "Latin", label: "Latin" },
  { value: "Latin Blues", label: "Latin Blues" },
  { value: "Latin Classical", label: "Latin Classical" },
  { value: "Latin Country", label: "Latin Country" },
  { value: "Latin Dance", label: "Latin Dance" },
  { value: "Latin Folk", label: "Latin Folk" },
  { value: "Latin Fusion", label: "Latin Fusion" },
  { value: "Latin Hip Hop", label: "Latin Hip Hop" },
  { value: "Latin House", label: "Latin House" },
  { value: "Latin Jazz", label: "Latin Jazz" },
  { value: "Latin Metal", label: "Latin Metal" },
  { value: "Latin Pop", label: "Latin Pop" },
  { value: "Latin Punk", label: "Latin Punk" },
  { value: "Latin Rap", label: "Latin Rap" },
  { value: "Latin Rock", label: "Latin Rock" },
  { value: "Latin Soul", label: "Latin Soul" },
  { value: "Latin Techno", label: "Latin Techno" },
  { value: "Latin Trance", label: "Latin Trance" },
  { value: "Latino Pop", label: "Latino Pop" },
  { value: "Latino Rock", label: "Latino Rock" },
  { value: "Latinohouse", label: "Latinohouse" },
  { value: "Latinojazz", label: "Latinojazz" },
  { value: "Latinopop", label: "Latinopop" },
  { value: "Latinorock", label: "Latinorock" },
  { value: "Levantine Folk", label: "Levantine Folk" },
  { value: "Levantine Hip Hop", label: "Levantine Hip Hop" },
  { value: "Levantine Jazz", label: "Levantine Jazz" },
  { value: "Levantine Pop", label: "Levantine Pop" },
  { value: "Levantine Rock", label: "Levantine Rock" },
  { value: "Light Rock", label: "Light Rock" },
  { value: "Lightblues", label: "Lightblues" },
  { value: "Lightcountry", label: "Lightcountry" },
  { value: "Lightfolk", label: "Lightfolk" },
  { value: "Lightjazz", label: "Lightjazz" },
  { value: "Lightmetal", label: "Lightmetal" },
  { value: "Lightpop", label: "Lightpop" },
  { value: "Lightreggae", label: "Lightreggae" },
  { value: "Lightrock", label: "Lightrock" },
  { value: "Lo-fi", label: "Lo-fi" },
  { value: "Lo-fi Blues", label: "Lo-fi Blues" },
  { value: "Lo-fi Folk", label: "Lo-fi Folk" },
  { value: "Lo-fi Hip Hop", label: "Lo-fi Hip Hop" },
  { value: "Lo-fi Jazz", label: "Lo-fi Jazz" },
  { value: "Lo-fi Metal", label: "Lo-fi Metal" },
  { value: "Lo-fi Pop", label: "Lo-fi Pop" },
  { value: "Lo-fi Rock", label: "Lo-fi Rock" },
  { value: "Lofi Hip Hop", label: "Lofi Hip Hop" },
  { value: "Lofi Pop", label: "Lofi Pop" },
  { value: "Lofi Rock", label: "Lofi Rock" },
  { value: "Lofi-electronica", label: "Lofi-electronica" },
  { value: "Lofi-jazz", label: "Lofi-jazz" },
  { value: "Lofi-rap", label: "Lofi-rap" },
  { value: "Lofi-rock", label: "Lofi-rock" },
  { value: "Lofi-electronica", label: "Lofi-electronica" },
  { value: "Lofi-jazz", label: "Lofi-jazz" },
  { value: "Lofi-rap", label: "Lofi-rap" },
  { value: "Lofi-rock", label: "Lofi-rock" },
  { value: "Lofi-electronica", label: "Lofi-electronica" },
  { value: "Lofi-jazz", label: "Lofi-jazz" },
  { value: "Lofi-rap", label: "Lofi-rap" },
  { value: "Lofi-rock", label: "Lofi-rock" },
  { value: "Loud Rock", label: "Loud Rock" },
  { value: "Low-fi", label: "Low-fi" },
  { value: "Low-fi Hip Hop", label: "Low-fi Hip Hop" },
  { value: "Low-fi Jazz", label: "Low-fi Jazz" },
  { value: "Low-fi Pop", label: "Low-fi Pop" },
  { value: "Low-fi Rock", label: "Low-fi Rock" },
  { value: "Lowfi", label: "Lowfi" },
  { value: "Lowfi Hip Hop", label: "Lowfi Hip Hop" },
  { value: "Lowfi Jazz", label: "Lowfi Jazz" },
  { value: "Lowfi Pop", label: "Lowfi Pop" },
  { value: "Lowfi Rock", label: "Lowfi Rock" },
  { value: "M-rap", label: "M-rap" },
  { value: "M-rap Pop", label: "M-rap Pop" },
  { value: "M-rap Rock", label: "M-rap Rock" },
  { value: "Mainstream Pop", label: "Mainstream Pop" },
  { value: "Mainstream Rap", label: "Mainstream Rap" },
  { value: "Mainstream Rock", label: "Mainstream Rock" },
  { value: "Majestic Rock", label: "Majestic Rock" },
  { value: "Mandopop", label: "Mandopop" },
  { value: "Maracatu", label: "Maracatu" },
  { value: "March", label: "March" },
  { value: "March Pop", label: "March Pop" },
  { value: "March Rock", label: "March Rock" },
  { value: "Mariachi", label: "Mariachi" },
  { value: "Mariachi Hip Hop", label: "Mariachi Hip Hop" },
  { value: "Mariachi Jazz", label: "Mariachi Jazz" },
  { value: "Mariachi Pop", label: "Mariachi Pop" },
  { value: "Mariachi Rock", label: "Mariachi Rock" },
  { value: "Mbalax", label: "Mbalax" },
  { value: "Mbube", label: "Mbube" },
  { value: "Merseybeat", label: "Merseybeat" },
  { value: "Metal", label: "Metal" },
  { value: "Metal Blues", label: "Metal Blues" },
  { value: "Metal Fusion", label: "Metal Fusion" },
  { value: "Metal Pop", label: "Metal Pop" },
  { value: "Metal Punk", label: "Metal Punk" },
  { value: "Metal Rap", label: "Metal Rap" },
  { value: "Metal Rock", label: "Metal Rock" },
  { value: "Metal Soul", label: "Metal Soul" },
  { value: "Metal Techno", label: "Metal Techno" },
  { value: "Metal Trance", label: "Metal Trance" },
  { value: "Metalcore", label: "Metalcore" },
  { value: "Metalhouse", label: "Metalhouse" },
  { value: "Metalpop", label: "Metalpop" },
  { value: "Metalrap", label: "Metalrap" },
  { value: "Metalrock", label: "Metalrock" },
  { value: "Metalsoul", label: "Metalsoul" },
  { value: "Metaltechno", label: "Metaltechno" },
  { value: "Metaltrance", label: "Metaltrance" },
  { value: "Middle Eastern Classical", label: "Middle Eastern Classical" },
  { value: "Middle Eastern Folk", label: "Middle Eastern Folk" },
  { value: "Middle Eastern Jazz", label: "Middle Eastern Jazz" },
  { value: "Middle Eastern Pop", label: "Middle Eastern Pop" },
  { value: "Middle Eastern Rock", label: "Middle Eastern Rock" },
  { value: "Midwest Hip Hop", label: "Midwest Hip Hop" },
  { value: "Midwest Jazz", label: "Midwest Jazz" },
  { value: "Midwest Pop", label: "Midwest Pop" },
  { value: "Midwest Punk", label: "Midwest Punk" },
  { value: "Midwest Rap", label: "Midwest Rap" },
  { value: "Midwest Rock", label: "Midwest Rock" },
  { value: "Midwest Soul", label: "Midwest Soul" },
  { value: "Midwest-jazz", label: "Midwest-jazz" },
  { value: "Midwest-jazz Pop", label: "Midwest-jazz Pop" },
  { value: "Midwest-punk", label: "Midwest-punk" },
  { value: "Midwest-rap", label: "Midwest-rap" },
  { value: "Midwest-rock", label: "Midwest-rock" },
  { value: "Milonga", label: "Milonga" },
  { value: "Minimal Electronica", label: "Minimal Electronica" },
  { value: "Minimal Hip Hop", label: "Minimal Hip Hop" },
  { value: "Minimal Jazz", label: "Minimal Jazz" },
  { value: "Minimal Pop", label: "Minimal Pop" },
  { value: "Minimal Rock", label: "Minimal Rock" },
  { value: "Minimal Techno", label: "Minimal Techno" },
  { value: "Minimal Trance", label: "Minimal Trance" },
  { value: "Minimo", label: "Minimo" },
  { value: "Minimo Jazz", label: "Minimo Jazz" },
  { value: "Minimo Pop", label: "Minimo Pop" },
  { value: "Minimo Rock", label: "Minimo Rock" },
  { value: "Minimalrock", label: "Minimalrock" },
  { value: "Minitecho", label: "Minitecho" },
  { value: "Minimaltechno", label: "Minimaltechno" },
  { value: "Minimatrance", label: "Minimatrance" },
  { value: "Minimalpop", label: "Minimalpop" },
  { value: "Minimaljazz", label: "Minimaljazz" },
  { value: "Minimalhiphop", label: "Minimalhiphop" },
  { value: "Minimalblues", label: "Minimalblues" },
  { value: "Minimalamericana", label: "Minimalamericana" },
  { value: "Minimalfolk", label: "Minimalfolk" },
  { value: "Minimalrock", label: "Minimalrock" },
  { value: "Minimaltrance", label: "Minimaltrance" },
  { value: "Minimaltechno", label: "Minimaltechno" },
  { value: "Minimablues", label: "Minimablues" },
  { value: "Minimalpop", label: "Minimalpop" },
  { value: "Minimaljazz", label: "Minimaljazz" },
  { value: "Minimalhiphop", label: "Minimalhiphop" },
  { value: "Minimalfolk", label: "Minimalfolk" },
  { value: "Minimalamericana", label: "Minimalamericana" },
  { value: "Minimaltrance", label: "Minimaltrance" },
  { value: "Minimaltechno", label: "Minimaltechno" },
  { value: "Minimalrock", label: "Minimalrock" },
  { value: "Minimalhiphop", label: "Minimalhiphop" },
  { value: "Minimaljazz", label: "Minimaljazz" },
  { value: "Minimalpop", label: "Minimalpop" },
  { value: "Minimaltrance", label: "Minimaltrance" },
  { value: "Minimaltechno", label: "Minimaltechno" },
  { value: "Minimalrock", label: "Minimalrock" },
  { value: "Minimalfolk", label: "Minimalfolk" },
  { value: "Minimalamericana", label: "Minimalamericana" },
  { value: "Minimaltrance", label: "Minimaltrance" },
  { value: "Minimaltechno", label: "Minimaltechno" },
  { value: "Minimalrock", label: "Minimalrock" },
  { value: "Minimalfolk", label: "Minimalfolk" },
  { value: "Minimalamericana", label: "Minimalamericana" },
  { value: "Minimaljazz", label: "Minimaljazz" },
  { value: "Minimalpop", label: "Minimalpop" },
  { value: "Minimalhiphop", label: "Minimalhiphop" },
  { value: "Minimalfolk", label: "Minimalfolk" },
  { value: "Minimalamericana", label: "Minimalamericana" },
  { value: "Minimalrock", label: "Minimalrock" },
  { value: "Minimaltrance", label: "Minimaltrance" },
  { value: "Minimaltechno", label: "Minimaltechno" },
  { value: "Minimalhiphop", label: "Minimalhiphop" },
  { value: "Minimaljazz", label: "Minimaljazz" },
  { value: "Minimalpop", label: "Minimalpop" },
  { value: "Minimaltrance", label: "Minimaltrance" },
  { value: "Minimaltechno", label: "Minimaltechno" },
  { value: "Minimalrock", label: "Minimalrock" },
  { value: "Minimalfolk", label: "Minimalfolk" },
  { value: "Minimalamericana", label: "Minimalamericana" },
  { value: "Minimaljazz", label: "Minimaljazz" },
  { value: "Minimalpop", label: "Minimalpop" },
  { value: "Minimalhiphop", label: "Minimalhiphop" },
  { value: "Minimalfolk", label: "Minimalfolk" },
  { value: "Minimalamericana", label: "Minimalamericana" },
  { value: "Minimalrock", label: "Minimalrock" },
  { value: "Minimaltrance", label: "Minimaltrance" },
  { value: "Minimaltechno", label: "Minimaltechno" },
  { value: "Minimalamericana", label: "Minimalamericana" },
  { value: "Minimalfolk", label: "Minimalfolk" },
  { value: "Minimaljazz", label: "Minimaljazz" },
  { value: "Minimalpop", label: "Minimalpop" },
  { value: "Minimalrock", label: "Minimalrock" },
  { value: "Minimaltrance", label: "Minimaltrance" },
  { value: "Minimaltechno", label: "Minimaltechno" },
  { value: "Minimalamericana", label: "Minimalamericana" },
  { value: "Minimalfolk", label: "Minimalfolk" },
  { value: "Minimaljazz", label: "Minimaljazz" },
  { value: "Minimalpop", label: "Minimalpop" },
  { value: "Minimalrock", label: "Minimalrock" },
  { value: "Minimaltrance", label: "Minimaltrance" },
  { value: "Minimaltechno", label: "Minimaltechno" },
  { value: "Minimalamericana", label: "Minimalamericana" },
  { value: "Minimalfolk", label: "Minimalfolk" },
  { value: "Minimaljazz", label: "Minimaljazz" },
  { value: "Minimalpop", label: "Minimalpop" },
  { value: "Minimalrock", label: "Minimalrock" },
  { value: "Minimaltrance", label: "Minimaltrance" },
  { value: "Minimaltechno", label: "Minimaltechno" },
  { value: "Minimalamericana", label: "Minimalamericana" },
  { value: "Minimalfolk", label: "Minimalfolk" },
  { value: "Minimaljazz", label: "Minimaljazz" },
  { value: "Minimalpop", label: "Minimalpop" },
  { value: "Minimalrock", label: "Minimalrock" },
  { value: "Minimaltrance", label: "Minimaltrance" },
  { value: "Minimaltechno", label: "Minimaltechno" },
  { value: "Minimalamericana", label: "Minimalamericana" },
  { value: "Minimalfolk", label: "Minimalfolk" },
  { value: "Minimaljazz", label: "Minimaljazz" },
  { value: "Minimalpop", label: "Minimalpop" },
  { value: "Minimalrock", label: "Minimalrock" },
  { value: "Minimaltrance", label: "Minimaltrance" },
  { value: "Minimaltechno", label: "Minimaltechno" },
  { value: "Minimalamericana", label: "Minimalamericana" },
  { value: "Minimalfolk", label: "Minimalfolk" },
  { value: "Minimaljazz", label: "Minimaljazz" },
  { value: "Minimalpop", label: "Minimalpop" },
  { value: "Minimalrock", label: "Minimalrock" },
  { value: "Minimaltrance", label: "Minimaltrance" },
  { value: "Minimaltechno", label: "Minimaltechno" },
  { value: "Minimalamericana", label: "Minimalamericana" },
  { value: "Minimalfolk", label: "Minimalfolk" },
  { value: "Minimaljazz", label: "Minimaljazz" },
  { value: "Minimalpop", label: "Minimalpop" },
  { value: "Minimalrock", label: "Minimalrock" },
  { value: "Minimaltrance", label: "Minimaltrance" },
  { value: "Minimaltechno", label: "Minimaltechno" },
  { value: "Minimalamericana", label: "Minimalamericana" },
  { value: "Minimalfolk", label: "Minimalfolk" },
  { value: "Minimaljazz", label: "Minimaljazz" },
  { value: "Minimalpop", label: "Minimalpop" },
  { value: "Minimalrock", label: "Minimalrock" },
  { value: "Minimaltrance", label: "Minimaltrance" },
  { value: "Minimaltechno", label: "Minimaltechno" },
  { value: "Minimalamericana", label: "Minimalamericana" },
  { value: "Minimalfolk", label: "Minimalfolk" },
  { value: "Minimaljazz", label: "Minimaljazz" },
  { value: "Minimalpop", label: "Minimalpop" },
  { value: "Minimalrock", label: "Minimalrock" },
  { value: "Minimaltrance", label: "Minimaltrance" },
  { value: "Minimaltechno", label: "Minimaltechno" },
  { value: "Minimalamericana", label: "Minimalamericana" },
  { value: "Minimalfolk", label: "Minimalfolk" },
  { value: "Minimaljazz", label: "Minimaljazz" },
  { value: "Minimalpop", label: "Minimalpop" },
  { value: "Minimalrock", label: "Minimalrock" },
  { value: "Minimaltrance", label: "Minimaltrance" },
  { value: "Minimaltechno", label: "Minimaltechno" },
  { value: "Minimalamericana", label: "Minimalamericana" },
  { value: "Minimalfolk", label: "Minimalfolk" },
  { value: "Minimaljazz", label: "Minimaljazz" },
  { value: "Minimalpop", label: "Minimalpop" },
  { value: "Minimalrock", label: "Minimalrock" },
  { value: "Minimaltrance", label: "Minimaltrance" },
  { value: "Minimaltechno", label: "Minimaltechno" },
  { value: "Minimalamericana", label: "Minimalamericana" },
  { value: "Minimalfolk", label: "Minimalfolk" },
  { value: "Minimaljazz", label: "Minimaljazz" },
  { value: "Minimalpop", label: "Minimalpop" },
  { value: "Minimalrock", label: "Minimalrock" },
  { value: "Minimaltrance", label: "Minimaltrance" },
  { value: "Minimaltechno", label: "Minimaltechno" },
  { value: "Minimalamericana", label: "Minimalamericana" },
  { value: "Minimalfolk", label: "Minimalfolk" },
  { value: "Minimaljazz", label: "Minimaljazz" },
  { value: "Minimalpop", label: "Minimalpop" },
  { value: "Minimalrock", label: "Minimalrock" },
  { value: "Minimaltrance", label: "Minimaltrance" },
  { value: "Minimaltechno", label: "Minimaltechno" },
  { value: "Minimalamericana", label: "Minimalamericana" },
  { value: "Minimalfolk", label: "Minimalfolk" },
  { value: "Minimaljazz", label: "Minimaljazz" },
  { value: "Minimalpop", label: "Minimalpop" },
  { value: "Minimalrock", label: "Minimalrock" },
  { value: "Minimaltrance", label: "Minimaltrance" },
  { value: "Minimaltechno", label: "Minimaltechno" },
  { value: "Minimalamericana", label: "Minimalamericana" },
  { value: "Minimalfolk", label: "Minimalfolk" },
  { value: "Minimaljazz", label: "Minimaljazz" },
  { value: "Minimalpop", label: "Minimalpop" },
  { value: "Minimalrock", label: "Minimalrock" },
  { value: "Minimaltrance", label: "Minimaltrance" },
  { value: "Minimaltechno", label: "Minimaltechno" },
  { value: "Minimalamericana", label: "Minimalamericana" },
  { value: "Minimalfolk", label: "Minimalfolk" },
  { value: "Minimaljazz", label: "Minimaljazz" },
  { value: "Minimalpop", label: "Minimalpop" },
  { value: "Minimalrock", label: "Minimalrock" },
  { value: "Minimaltrance", label: "Minimaltrance" },
  { value: "Minimaltechno", label: "Minimaltechno" },
  { value: "Minimalamericana", label: "Minimalamericana" },
  { value: "Minimalfolk", label: "Minimalfolk" },
  { value: "Minimaljazz", label: "Minimaljazz" },
  { value: "Minimalpop", label: "Minimalpop" },
  { value: "Minimalrock", label: "Minimalrock" },
  { value: "Minimaltrance", label: "Minimaltrance" },
  { value: "Minimaltechno", label: "Minimaltechno" },
  { value: "Minimalamericana", label: "Minimalamericana" },
]