export const genres = [
  { value: "A Cappella", label: "Abstract Hip Hop" },
  { value: "Accordion", label: "Acid House" },
  { value: "Acoustic Pop", label: "Adult Standards" },
  { value: "Afrobeat", label: "Aggrotech" },
  { value: "Album Rock", label: "Alternative Americana" },
  { value: "Alternative Metalcore", label: "Alternative Pop" },
  { value: "Alternative Rock", label: "Ambient" },
  { value: "Ambient Psychill", label: "Anarcho-punk" },
  { value: "Anime", label: "Anti-folk" },
  { value: "Arab Folk", label: "Argentine Indie" },
  { value: "Armenian Folk", label: "Art Rock" },
  { value: "Atmospheric Black Metal", label: "Athens Indie" },
  { value: "Atmospheric Post Rock", label: "Avant-Garde" },
  { value: "Ballroom", label: "Baroque Pop" },
  { value: "Bass Music", label: "Beatboxing" },
  { value: "Bebop", label: "Big Band" },
  { value: "Bitpop", label: "Black Metal" },
  { value: "Bluegrass", label: "Blues Rock" },
  { value: "Boogie Woogie", label: "Bossa Nova" },
  { value: "Bounce", label: "Brazilian Pop" },
  { value: "Breakbeat", label: "Britpop" },
  { value: "Brostep", label: "Bubblegum Pop" },
  { value: "Cajun", label: "Calypso" },
  { value: "Cantopop", label: "Celtic" },
  { value: "Chicago Blues", label: "Chillwave" },
  { value: "Chiptune", label: "Choral" },
  { value: "Christian Rock", label: "City Pop" },
  { value: "Classical", label: "Cloud Rap" },
  { value: "Club", label: "Comedy" },
  { value: "Cool Jazz", label: "Country Blues" },
  { value: "Country Pop", label: "Crossover Jazz" },
  { value: "Crunk", label: "Dance Hall" },
  { value: "Dance-Punk", label: "Dance-Pop" },
  { value: "Darkwave", label: "Death Metal" },
  { value: "Deep House", label: "Desert Blues" },
  { value: "Disco", label: "Dixieland" },
  { value: "Djent", label: "Doo-wop" },
  { value: "Downtempo", label: "Dream Pop" },
  { value: "Drill", label: "Drum and Bass" },
  { value: "Dub", label: "Dubstep" },
  { value: "Electro House", label: "Electro Swing" },
  { value: "Electropop", label: "Emo" },
  { value: "Eurobeat", label: "Experimental" },
  { value: "Fado", label: "Folk Punk" },
  { value: "Folk Rock", label: "Free Jazz" },
  { value: "Funk Rock", label: "Future Bass" },
  { value: "Gabber", label: "Garage Rock" },
  { value: "Glam Metal", label: "Gospel" },
  { value: "Grime", label: "Grunge" },
  { value: "Hard Rock", label: "Hardcore Hip Hop" },
  { value: "Hardstyle", label: "Heavy Metal" },
  { value: "Highlife", label: "Hip Hop" },
  { value: "House", label: "Hyperpop" },
  { value: "IDM", label: "Indie Folk" },
  { value: "Indie Pop", label: "Indie Rock" },
  { value: "Industrial", label: "Italo Disco" },
  { value: "J-pop", label: "Jazz Fusion" },
  { value: "K-pop", label: "Krautrock" },
  { value: "Latin Jazz", label: "Latin Pop" },
  { value: "Liquid Funk", label: "Lo-fi" },
  { value: "Madchester", label: "Mainstream Rock" },
  { value: "Mariachi", label: "Math Rock" },
  { value: "Melodic Death Metal", label: "Memphis Blues" },
  { value: "Metalcore", label: "Minimal Techno" },
  { value: "Modern Blues", label: "Motown" },
  { value: "Neoclassical", label: "Neo-Soul" },
  { value: "New Age", label: "New Wave" },
  { value: "Noise Pop", label: "Noise Rock" },
  { value: "Nu Metal", label: "Nu-Disco" },
  { value: "Opera", label: "Orchestral" },
  { value: "Pagan Metal", label: "Pop Punk" },
  { value: "Pop Rock", label: "Post-Grunge" },
  { value: "Post-Hardcore", label: "Post-Metal" },
  { value: "Post-Punk", label: "Post-Rock" },
  { value: "Power Metal", label: "Progressive House" },
  { value: "Progressive Metal", label: "Progressive Rock" },
  { value: "Psybient", label: "Psychedelic Rock" },
  { value: "Punk Blues", label: "Punk Rock" },
  { value: "R&B", label: "Rap Rock" },
  { value: "Reggae", label: "Reggaeton" },
  { value: "Rockabilly", label: "Salsa" },
  { value: "Samba", label: "Shoegaze" },
  { value: "Ska Punk", label: "Soft Rock" },
  { value: "Soul Jazz", label: "Southern Rock" },
  { value: "Speed Metal", label: "Stoner Rock" },
  { value: "Surf Rock", label: "Synthwave" },
  { value: "Techno", label: "Thrash Metal" },
  { value: "Trance", label: "Trap" },
  { value: "Trip Hop", label: "Tropical House" },
  { value: "UK Garage", label: "Vaporwave" },
  { value: "Viking Metal", label: "Vocal Jazz" },
  { value: "Worldbeat", label: "Yacht Rock" },
  { value: "Zydeco", label: "Afro-Cuban" },
  { value: "Afro-Funk", label: "Afro-Jazz" },
  { value: "Afro-Pop", label: "Afro-Soul" },
  { value: "Afro-Trap", label: "Alt-Country" },
  { value: "Alt-Dance", label: "Alt-Hip Hop" },
  { value: "Alt-Pop", label: "Alt-R&B" },
  { value: "Alt-Rock", label: "Alt-Soul" },
  { value: "Ambient Pop", label: "Ambient House" },
  { value: "Ambient Techno", label: "Art Punk" },
  { value: "Asian Pop", label: "Avant-Folk" },
  { value: "Avant-Jazz", label: "Barbershop" },
  { value: "Blues", label: "Celtic Rock" },
  { value: "Chamber Pop", label: "Chillout" },
  { value: "Chiptune Pop", label: "Classical Crossover" },
  { value: "Classical Piano", label: "Classic Country" },
  { value: "Classic Rock", label: "Coldwave" },
  { value: "Comedy Rap", label: "Country Rock" },
  { value: "Country Rap", label: "Country Soul" },
  { value: "Crunkcore", label: "Cyberpunk" },
  { value: "Dark Ambient", label: "Dark Cabaret" },
  { value: "Deathcore", label: "Deephouse" },
  { value: "Dreamwave", label: "Drumstep" },
  { value: "Dystopian", label: "Electroclash" },
  { value: "Electro Funk", label: "Electro Jazz" },
  { value: "Electro Rock", label: "Emo Pop" },
  { value: "Epic Metal", label: "Ethereal Wave" },
  { value: "Folk Metal", label: "Folk Pop" },
  { value: "Garage", label: "Gothic Metal" },
  { value: "Gothic Rock", label: "Groove Metal" },
  { value: "Happy Hardcore", label: "Hard Dance" },
  { value: "Hard Trance", label: "Hardcore Punk" },
  { value: "Horrorcore", label: "Indie Dance" },
  { value: "Indie Electronic", label: "Indie Jazz" },
  { value: "Indie Soul", label: "Jazz Blues" },
  { value: "Jazz Funk", label: "Jungle" },
  { value: "Latin Rock", label: "Leftfield" },
  { value: "Lounge", label: "Lovers Rock" },
  { value: "Metal", label: "New Romantic" },
  { value: "Orchestral Pop", label: "Outlaw Country" },
  { value: "Phonk", label: "Pop Rap" },
  { value: "Pop Soul", label: "Prog Metal" },
  { value: "Psych Folk", label: "Rave" },
  { value: "Reggae Fusion", label: "Retro Swing" },
  { value: "Riot Grrrl", label: "Roots Reggae" },
  { value: "Screamo", label: "Sludge Metal" },
  { value: "Slowcore", label: "Smooth Jazz" },
  { value: "Soundtrack", label: "Southern Gospel" },
  { value: "Space Rock", label: "Steampunk" },
  { value: "Swamp Pop", label: "Synth Pop" },
  { value: "Tango", label: "Tech House" },
  { value: "Tech Trance", label: "Traditional Pop" },
  { value: "Trap Metal", label: "Trap Soul" },
  { value: "Tribal House", label: "Tropical Pop" },
  { value: "Turntablism", label: "Urban Blues" },
  { value: "Vaportrap", label: "Wave" },
  { value: "West Coast Rap", label: "Western Swing" },
  { value: "Witch House", label: "Y2K Pop" },
  { value: "Zouk", label: "Zumba" },
];
